### ISSUE TITLE
远程控制、远程诊断调用页面

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#1003]
- 写2个测试页面，下发远程控制指令和远程诊断指令
 - 远程控制接口 VehicleDataController ：remoteControl
 - 远程诊断接口 VehicleDataController ：sentDiagnosticToVehicle

**Comment by flowweerr** [comment]
转发给相应人员做

**Comment by AceBear** [comment]
只写API, 控制命令相关的内容问 @jack-luj

**Comment by TeemolSparrow** [comment]
[#540](https://github.com/HP-Enterprise/BriAir/pull/540)已完成远程控制API
