### ISSUE TITLE
安防密码

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#1010]
+ 每台车都有一个安防密码
+ 当给车向发送远程控制类指令时(如远程开关车门,闪烁前灯等等),需要验证输入的安防密码是否正确
+ 用户不可以自己修改安防密码,只能通过车辆销售的4S店的客服来修改
+ 系统中也没有任何位置可以查看安防密码

**Comment by Septemberwh** [comment]
9204a59fd67f52c7d41d472cadd3257fe05e1e8f  已完成
