### ISSUE TITLE
消息管理-推送消息

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#1033]
[消息接口定义-草稿1104.docx](https://github.com/HP-Enterprise/BriAir/files/29806/-.1104.docx)
 - 根据 **消息接口定义-草稿1104.docx** 文档修改 *MessageController* API中 *pushMessageToDevice* 方法输入参数
     * @param sourceId    发送用户id<br>
     * @param resourceFrom  数据来源 1 手机,2 车机<br>
     * @param targetId 目标对象id <br>
     * @param resourceTo 目标类型 1 手机,2 车机,3 短信,4 手机 车机 短信<br>
     * @param contentType 发送内容类型 1 表示text,2 表示文件<br>
     * @param textContent 发送内容文本<br>
     * @param targetType 目标对象类型 1 user ,2 organize<br>
     * @param msgFile 发送的附件<br>
 - 修改为如下参数：
     * @param sourceId    发送用户id<br>
     * @param resourceFrom  数据来源 1 手机,2 车机<br>
     * @param targetType 目标对象类型 1 user ,2 organize<br>
     * @param targetId 目标对象id <br>
     * @param resourceTo 目标类型 1 手机,2 车机,3 短信,4 手机 车机 短信<br>
     * @param Funtype 消息类型  1 即时通讯  2 推送消息
     * @param ptype    推送消息类型  
         -  1 远程控制
         -  2 故障提醒
         -  3 保养提醒
         -  4 位置分享
      	 -  5 智能寻车
     	 -  6 位置共享
         -  7 发送位置
       	 -  8 气囊报警
       	 -  9 防盗报警
     * @param contentType 发送内容类型 
       	 -  1 文本 
       	 -  2 音乐 
       	 -  3 图片 
       	 -  41 位置信息 
       	 -  42 位置共享开始  
       	 -  43 位置共享结束
     * @param textContent 发送内容文本、经纬度<br>
     * @param msgFile 发送的附件<br>
 - 在*pushMessageToDevice* 里增加逻辑，根据不同的推送消息的输入，根据 **消息接口定义-草稿1104.docx** 文档，push不同的推送消息。

**Comment by flowweerr** [comment]
- 根据 **消息接口定义-草稿1104.docx** 文档修改 *MessageController* API中 *pushMessageToDevice* 方法输入参数
     * @param sourceId    发送用户id<br>
     * @param resourceFrom  数据来源 1 手机,2 车机<br>
     * @param targetId 目标对象id <br>
     * @param resourceTo 目标类型 1 手机,2 车机,3 短信,4 手机 车机 短信<br>
     * @param contentType 发送内容类型 1 表示text,2 表示文件<br>
     * @param textContent 发送内容文本<br>
     * @param targetType 目标对象类型 1 user ,2 organize<br>
     * @param msgFile 发送的附件<br>
 - 修改为如下参数：
     * @param sourceId    发送用户id<br>
     * @param resourceFrom  数据来源 1 手机,2 车机<br>
     * @param targetType 目标对象类型 1 user ,2 organize<br>
     * @param targetId 目标对象id <br>
     * @param resourceTo 目标类型 1 手机,2 车机,3 短信,4 手机 车机 短信<br>
     * @param Funtype 消息类型  1 即时通讯  2 推送消息
     * @param ptype    推送消息类型  
         -  1 远程控制
         -  2 故障提醒
         -  3 保养提醒
         -  4 位置分享
      	 -  5 智能寻车
     	 -  6 位置共享
         -  7 发送位置
       	 -  8 气囊报警
       	 -  9 防盗报警
     * @param contentType 发送内容类型 
       	 -  1 文本 
       	 -  2 音乐 
       	 -  3 图片 
       	 -  41 位置信息 
       	 -  42 位置共享开始  
       	 -  43 位置共享结束
     * @param textContent 发送内容文本、经纬度<br>
     * @param msgFile 发送的附件<br>
 - 在*pushMessageToDevice* 里增加逻辑，根据不同的及时消息的输入，根据 **消息接口定义-草稿1104.docx** 文档，push不同的及时消息。

**Comment by liuyakun** [comment]
已完成 4db1a422cf3bac28c152cc2c2b4c960f39b5147b
