### ISSUE TITLE
消息管理-修改附件下发方式为下发url

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#1034]
[消息接口定义-草稿1104.docx](https://github.com/HP-Enterprise/BriAir/files/29804/-.1104.docx)
 - 目前我们消息是用对象下发消息，目前改变这种方式为下发url，根据 **消息接口定义-草稿1104.docx** 文档规范修改接口

**Comment by liuyakun** [comment]
已完成 4db1a422cf3bac28c152cc2c2b4c960f39b5147b
