### ISSUE TITLE
CMPP

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#1043]
## 中国移动CMPP短信网关

+ 根据中国移动CMPP3.0协议,实现接入中移动短信网关功能

[《中国移动通信互联网短信网关接口协议CMPP(v3.0.0)》](http://ic-media.oss-cn-hangzhou.aliyuncs.com/2015%2F11%2F%E4%B8%AD%E5%9B%BD%E7%A7%BB%E5%8A%A8%E9%80%9A%E4%BF%A1%E4%BA%92%E8%81%94%E7%BD%91%E7%9F%AD%E4%BF%A1%E7%BD%91%E5%85%B3%E6%8E%A5%E5%8F%A3%E5%8D%8F%E8%AE%AECMPP%EF%BC%88V3.0.0%EF%BC%89.docx)

**Comment by jack-luj** [comment]
目前已完成文本短信发送以及接收，已有简单HTTP API接口提供，部分收发参数需要实测，二进制发送及接收迟一些补上

**Comment by jack-luj** [comment]
二进制短信收发已经支持，CMPP下发的短信目前接收存储在redis

**Comment by jack-luj** [comment]
暂不提PR，等待实测网关......

**Comment by jack-luj** [comment]
SMS下的dev-cmpp3.0分支
https://github.com/HP-Enterprise/SMS/tree/dev-cmpp3.0
请不要删除！
