### ISSUE TITLE
JAVA:4S处理预约保养 PUT /api/org/{rid}/reservation

### ISSUE THREAD

**Issue by wangh2015** [HP-Enterprise/BriAir#1065]
#981 4S店收到后,可以接受预约,也可以拒绝预约.
用户会收到通知消息,他的预约请求被批准了,或被拒绝了,如果是拒绝了,还需要附有简短的拒绝原因

**Comment by tiandashen** [comment]
459f199fcf1b5738391a6bd75fc936c3b4c9f55a
初步完成

**Comment by tiandashen** [comment]
5d9c51dabef5c928a7fa56119076b6c738596707
已完成
