### ISSUE TITLE
免责声明、注册协议接口 

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#1069]
##### 免责声明、注册协议接口 
 - 免责声明接口 url可以写在配置文件里
    -  输入：http://ip:port/api/exemption/url
    -  返回：免责声明地址url
 - 注册协议接口 url可以写在配置文件里
    -  输入：http://ip:port/api/registeragreement/url
    -  返回：注册协议地址url

#1049

**Comment by AceBear** [comment]
写一个API返回 #925 增加的那个HTML网页的地址即可

**Comment by wangh2015** [comment]
86352cb959398df600e2fc9f189b484194c31394 已测试，完成
