### ISSUE TITLE
SQL: 内置管理员权限分配

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#107]
+ 使用SQL,内建一个 权限组"sysadmin"
+ 给该组分配权限 admin + login
+ 给该组分配唯一一个用户( #106 系统内置管理员 )

参见 #80 管理员用户管理

**Comment by tiandashen** [comment]
657296924d54ba707d094f46f72944c253e6b873
38964e2430316d17364ea3b03f9d7884023dda4f
