### ISSUE TITLE
车辆管理类-增加默认车辆字段

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#1071]
##### 车辆管理类-增加默认车辆字段
 - t_user_vehicle_relatived 表增加  default 默认车辆标识 1 默认 0 非默认
 - 车辆管理VehicleController类，修改createRelatived绑定方法，增加默认车辆字段
 - 增加修改默认车辆接口
 - 增加查询默认车辆接口

#1049

**Comment by TeemolSparrow** [comment]
已完成此任务
