### ISSUE TITLE
通讯录接口修改

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#1073]
##### 通讯录接口修改
 - 通讯录上传接口 createOrModifySlot 改为保存到数据库，并打标 是否可添加好友 1 可添加好友 2 不可添加好友
    - 输入：
       - uid	用户id
       - name	联系人名字
       - phone	联系人电话
    - 输入：成功失败结果

 - 通讯录查询接口  getSlots 
    - 输入：uid
    - 输出：
        - uid	用户id
        - name	联系人名字
        - phone	联系人电话
        - isuser	是否可添加好友 1 可添加好友 2 不可添加好友

#1049

**Comment by TeemolSparrow** [comment]
已完成此功能
