### ISSUE TITLE
HTTP: POST /api/org

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#108]
创建一个组织

一个组织包含以下属性:
+ 组织名称: 一般是中文的全称,或英文的,有可能有空格,最大支持128个汉字
+ 组织简码: 字母或数字,要求全局唯一,不区分大小写,最大支持 8个字符
+ 组织类型: 目前包含2类**华晨汽车** & **经销商** ,以后会扩充更多类型

参见 #109 组织机构管理

**Comment by bingshe** [comment]
已完成
