### ISSUE TITLE
用户名不应要求必须由字母+数字组合

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#11]
![name](https://cloud.githubusercontent.com/assets/5030312/9242625/1a26560c-41b7-11e5-824b-a69cc6c77dd8.gif)

#4

**Comment by jiangli0509** [comment]
那要用什么组合？中文字也可以吗？

**Comment by jiangli0509** [comment]
$ 、字母、下划线开头都行，后面的可以是数字、字母、下划线

**Comment by jiangli0509** [comment]
已完成
