### ISSUE TITLE
HTTP: GET /api/org/{oid}

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#110]
查询个单组织详情

参见 #109 组织机构管理 #108 创建组织

**Comment by 473104925** [comment]
目前正在熟悉工具的使用，因为之前在公司使用的是Myeclipse，对我们公司使用的idea开发工具完全不熟悉。
 
 
------------------ Original ------------------

**Comment by jiangli0509** [comment]
@473104925 分支：dev-orgapi
