### ISSUE TITLE
JS 更新用户头像

### ISSUE THREAD

**Issue by Septemberwh** [HP-Enterprise/BriAir#1111]
可参考uploadCtrl.js的上传功能[uploadCtrl.js#L134-L163](https://github.com/HP-Enterprise/BriAir/blob/dev-%231091/src/main/resources/static/scripts/controller/uploadCtrl.js#L134-L163)
REF #1091

**Comment by liuyakun** [comment]
已完成 c8151250ec8fac78a660de04e9d4026e746bce5d
