### ISSUE TITLE
单元测试需要保证unix下适用

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#1112]
下面这个单元测试不适合unix操作系统
不要写出这种单元测试

[ImageManagerTest.java#L48-L49](https://github.com/HP-Enterprise/BriAir/blob/ca2945384edf37f2512386612c5c81c46fbc416f/src/test/java/com/hp/briair/ImageManagerTest.java#L48-L49)

**Comment by wangh2015** [comment]
已测试
