### ISSUE TITLE
不合适的单元测试

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#1114]
下面这个单元测试无法适用于unix

[UploadControllerTest.java#L62-L63](https://github.com/HP-Enterprise/BriAir/blob/ca2945384edf37f2512386612c5c81c46fbc416f/src/test/java/com/hp/briair/UploadControllerTest.java#L62-L63)

**Comment by Septemberwh** [comment]
51941af927ec6ffbe2d44f85f15a8adb4a50225c 已完成
