### ISSUE TITLE
HTTP: POST /api/org/{org}/suborg

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#114]
向组织中添加子组织

+ 组织允许有上下级组织这种层级关系

参见 #109 组织机构管理

**Comment by bingshe** [comment]
已完成 dd55416010935d1073480cf71e8406401839f172

**Comment by jiangli0509** [comment]
判断子组织和父组织没有形成闭环，例如A组织有子组织为B，就不能再添加A组织为B的子组织。以此类推多层子组织也不能形成闭环。

**Comment by bingshe** [comment]
完成，请查收
