### ISSUE TITLE
JAVA: unchecked 汇总

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#1145]
$\src\main\java\com\hp\triclops\repository\PhoneBookRepositoryDAO.java:119: 警告: [unchecked] 对作为原始类型Iterable的成员的forEach(Consumer<? super T>)的调用未经过检查
        queryList.forEach(o -> {
                         ^
  其中, T是类型变量:
    T扩展已在接口 Iterable中声明的Object
1 个警告

**Comment by TeemolSparrow** [comment]
已消除此警告
