### ISSUE TITLE
HTTP: GET /api/org

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#116]
查询组织

支持以下查询参数
- pagesize,page,orderby:分页
- sub_oid,recursively:包含某个子组织的
- par_oid,recursively:父组织是某个组织的
- uid,recursively:包含某个用户的
- vid,recursively:包含某台车辆的
- type_key:某种特定类型的

参见 #109 组织机构管理

**Comment by jiangli0509** [comment]
建立org和user的关系表
建立org和vehicle的关系表

**Comment by jiangli0509** [comment]
@AceBear vid,recursively:包含某台车辆的 其中的vid应该是vin吗？

**Comment by bingshe** [comment]
852524eb09dfc5a7d12b16a68bda6873557b5ac6 查询

**Comment by AceBear** [comment]
不是,因为VIN码带有部分私隐性质,所以我们平时不使用VIN,而是使用VID
----- original message -----
@AceBear vid,recursively:包含某台车辆的 其中的vid应该是vin吗？
