### ISSUE TITLE
按地区查询群

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#1178]
###### 按地区查询群
本接口用于按地区查询群，带分页功能
###### 请求说明
url	http://ip:port/api/org/area
支持验证方式	密码验证
格式	json
请求方式	GET
是否需要鉴权	true

请求参数 根据用户token，过滤用户已经在的群
序号	参数名称	必填	描述
1	currentpage	否	当前页
2	pagesize	否	每页的条数
3	orderby	否	排序方法
4	areaid	是	地区id

###### 请求示例
http：//ip:port/api/org/area? currentpage=1& pagesize=20&areaid=4387

###### 返回参数

序号	参数名称	描述
1	orgName	群名称
2	breCode	群编号
3	typeKey	群类型
4	descript	群描述
5	id	群id
6	available	是否可用 0 失效 1 可用

###### 应答示例
 [{"id":2,"orgName":"testOrg1","breCode":"1234","typeKey":2,"descript":"奥迪经销商","available":0},{"id":1,"orgName":"华晨汽车","breCode":"BriAir","typeKey":1,"descript":"华晨汽车根组织(不可删除)","available":1}]

#1165

**Comment by Liujingguo91year** [comment]
已完成
Baiair  b5f8cfdf
