### ISSUE TITLE
授权管理

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#1179]
#### 授权管理
本接口提供授权功能，将车辆授权给好友使用
 - 请求说明
url	http://ip:port/api/vehicle/authorization
支持验证方式	密码验证
格式	json
请求方式	POST
是否需要鉴权	true

 - 请求参数
序号	参数名称	必填	描述
1	vid	是	车辆id
2	uid	是	授权用户id
3	starttime	是	授权开始时间
4	endtime	是	授权结束时间

 - 请求示例
http://ip:port/api/vehicle/authorization
{" vid ":"122"," uid ":"342"," starttime ":"2015-12-12 00:00:00"," endtime ":"2015-12-14 00:00:00"}

 - 返回参数
序号	参数名称	描述
1*	status	状态
2*	message	消息

 - 应答示例
{"status":"success","message":"授权成功"}

*********************************程序设计**********************************
1.设计一个授权entity
    - muid 车主uid
    - vid   车辆id
    - uid   授权用户id
    - starttime   授权开始时间
    - endtime   授权结束时间
    - 授权状态 0 授权开始 1 授权中 2 授权结束 
2.建立一个轮询程序，每天轮询一次，修改授权状态
    - 将状态为0且 starttime  < today < endtime的记录授权状态设置为1，开始授权 （t_user_vehicle_relatived 表增加记录 ）
    - 将状态为1且endtime < today 的记录授权状态设置为2，解除授权（t_user_vehicle_relatived表删除记录 ）

#1165

**Comment by TeemolSparrow** [comment]
已完成此功能
