### ISSUE TITLE
增加设置紧急联系人、查询紧急联系人功能

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#1180]
##### 查询紧急联系人
本接口用于查询紧急联系人
 - 请求说明
url	http://ip:port/api/user/{uid}/contacts
支持验证方式	密码验证
格式	json
请求方式	GET
是否需要鉴权	true

 - 请求参数
序号	参数名称	必填	描述
1	uid	是	用户id

 - 请求示例
http：//ip:port/api/user/1/contacts

 - 返回参数
序号	参数名称	描述
1*	id	用户id
2*	contacts	紧急联系人
3*	contactsPhone	紧急联系人电话

 - 应答示例
{"id":"1"," contacts ":"张三"," contactsPhone ":"13917222212"}

##### 设置紧急联系人
本接口用于设置紧急联系人

 - 请求说明
url	http://ip:port/api/user/{uid}/contacts
支持验证方式	密码验证
格式	json
请求方式	PUT
是否需要鉴权	true

 - 请求参数
序号	参数名称	必填	描述
1	uid	是	用户id
2	contacts	否	联系人
3	contactsPhone	是	联系人电话

 - 请求示例
http：//ip:port/api/user/1/contacts
{"uid":"jiangmieli2"," contacts ":"张三"," contactsPhone ":"13917222212"}

 - 返回参数
序号	参数名称	描述
1*	id	用户id
2*	name	姓名
3*	gender	性别
4*	nick	昵称
5*	phone	电话号码
6*	isVerified	是否验证
7*	contacts	紧急联系人
8*	contactsPhone	紧急联系人电话
9*	iconurl	头像url

 - 应答示例
{"name":"testUser1","password":"w123123","nick":"jiangmieli2","phone":"13296630211","gender":1, " contacts ":"张三"," contactsPhone ":"13917222212"}

#1165

**Comment by tiandashen** [comment]
5304bb831644306410627dec131af641d68d9d88
已完成
