### ISSUE TITLE
JAVA：PerfStatController

### ISSUE THREAD

**Issue by wangh2015** [HP-Enterprise/BriAir#1205]
基于[1183](https://github.com/HP-Enterprise/BriAir/tree/dev-apiCount-%231183) 开分支
实现两个方法:

http GET /api/perf/{key}
调用prefMgr.getCount()

#805

**Comment by tiandashen** [comment]
fd3cfbd7bae7c9875a3f0ed03f3ee1e579fea20a
已完成
