### ISSUE TITLE
蓝牙登陆

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#1209]
- 增加 蓝牙是否绑定有自动登录的接口 
     - 只是检查有没有，返回一个 true or false 即可 跟19.1不一样，不用返回用户list

#1165

**Comment by TeemolSparrow** [comment]
此接口已存在，不需要增加

[BluetoothAccountController](https://github.com/HP-Enterprise/BriAir/blob/dd6a562a4955b7eea7d05de0c03590c3a9b0ab6d/src/main/java/com/hp/briair/controller/BluetoothAccountController.java#L38-L49)
