### ISSUE TITLE
保养管理-根据城市查询4S店，返回电话，地址，城市

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#1219]
##### 建立4S店实体信息表 

   id  --4s店id
  oid  --所属组织id
   fSname  --4s店名称
   fSphone  --电话
   fSaddress  --地址
   city  --城市
   cityid --城市id
*************************接口设计*********************************
##### 根据城市查询4S点接口
 - 接口说明
本接口用于查询4S店信息。

 - 请求说明
url	http://ip:port/api/vehicle/{vid}/4S/{areaid}
格式	json
请求方式	GET

 - 请求参数
序号	参数名称	必填	描述
1	vid	是	车辆id
2	areaid	是	地区id

 - 请求示例
http：//ip:port/api/vehicle/3454/care/4343

 - 返回参数
序号	参数名称	描述
1*	id	4S店id
2*	fSname	4S店名称
3	fSphone 	4S店电话
4	fSaddress	4S店地址
5	city	城市
6	cityid	城市id

 - 应答示例
{"id":"1"，" fSname":"华晨4S1"，" fSphone":"13787676565"，" fSaddress ":"中山路78号"},{" fSname":"华晨4S2"，" fSphone":"13787676578"，" fSaddress ":"解放路78号"," city":"沈阳"," cityid":"12"}

#1165

**Comment by Liujingguo91year** [comment]
已完成
Briair
https://github.com/HP-Enterprise/BriAir/pull/1254/files
