### ISSUE TITLE
车辆管理修改

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#1220]
- 根据用户查询车辆接口增加：颜色、购买4S店、购买时间、车辆图片、电动-乘用标识

 - 车辆表增加
   vcolor	varchar(20) 颜色
   buystore varchar(100)	购买4S店
   buydate	 date 购买时间
   vpurl	varchar(200) 车辆图片url
   vtype	int default 1 车辆类型 1 乘用 2 电动 默认为1

**************************接口设计***************************** 
 - 根据用户查询车辆
本接口用于根据用户查询车辆

 - 请求说明
url	http://ip:port/api/vehicle/{uid}/vehicle
支持验证方式	密码验证
格式	json
请求方式	GET
是否需要鉴权	true

 - 请求参数
序号	参数名称	必填	描述
1	uid	是	用户id

 - 请求示例
http：//ip:port/api/vehicle/1/vehicle

 - 返回参数
序号	参数名称	描述
1*	VehicleShow	车辆信息
序号	参数名称	描述
1*	id	车辆id
2*	vin	车架号
3*	tboxsn	Tbox码
4*	vendor	厂家
5*	model	型号
6*	t_flag	车辆是否禁用
7*	displacement	排量
8*	license_plate	车牌号
9*	product_date	生产日期
10*	vflag	默认车辆标识 1 默认 0 非默认
11*	vcolor	颜色
12*	buystore	购买4S店
13*	buydate	购买时间
14*	vpurl	车辆图片url
15*	vtype	车辆类型 1 乘用 2 电动 默认为1

 - 应答示例
[{"id":2,"vin":"testVin","vendor":null,"model":null,"t_flag":null,"displacement":null,"license_plate":null,"product_date":-28800000,"tboxsn":"testTboxsn","oid":null, “vflag” :”0”, “vcolor” :”蓝色”, “buystore” :”中心店”, “buydate” :”2015-11-14 12:00:00”, “vpurl” :”http://ip:port/web/vpic?7”, “vtype” :”1”},{"id":3,"vin":"testVin1","vendor":null,"model":null,"t_flag":null,"displacement":null,"license_plate":null,"product_date":-28800000,"tboxsn":"testTboxsn","oid":null, “vflag” :”1”, “vcolor” :”红色”, “buystore” :”世贸店”, “buydate” :”2015-10-16 10:00:00”, “vpurl” :”http://ip:port/web/vpic?87”, “vtype” :”1”}]

#1165

**Comment by TeemolSparrow** [comment]
已完成此API升级
