### ISSUE TITLE
V0.1建议 用户注册页面 用户名和手机号输入框提示内容不准确

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#123]
路径：用户注册页面
现象：在“用户名”输入框中显示“选一个用户名”，在“手机号”输入框中显示您的手机号，见附件A
建议：将“用户名”输入框中的默认显示内容改为 输入一个用户名
![a](https://cloud.githubusercontent.com/assets/13793913/9622056/16ebc4cc-5161-11e5-89c3-ba10e873ddc9.jpg)

**Comment by dongliu1** [comment]
已完成

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
