### ISSUE TITLE
V0.1从其他登录页面返回到注册首页 页面右上角的输入框和按钮未显示出来

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#124]
路径：用户注册首页
操作：
1、在用户注册首页的右上角直接点击“登录”按钮（见附件A1）；
![a1](https://cloud.githubusercontent.com/assets/13793913/9621771/665c6eac-515d-11e5-86c9-5fd1b06d2a29.jpg)
2、接着在新的页面（见附件A2）中点击浏览器自带的返回按钮（见附件A2）
![a2](https://cloud.githubusercontent.com/assets/13793913/9621777/790c7826-515d-11e5-99ea-d6bf34257155.jpg)
现象：页面跳转回用户注册首页发现页面右上角的“用户名输入框”、“密码输入框”和“登录”按钮未显示出来（见附件A3）
![a3](https://cloud.githubusercontent.com/assets/13793913/9621780/7dde3ab0-515d-11e5-949c-a0b515ba2ef1.jpg)
期望：从其他页面返回到用户注册首页时，“用户名输入框”、“密码输入框”和“登录”按钮能正常显示出来

**Comment by AceBear** [comment]
```
$scope.$on('$routeChangeSuccess', function(scope, next, current){
    // .... do something....
});
```

**Comment by wjgao** [comment]
v0.5版本上，此问题已处理，复测通过，关闭
