### ISSUE TITLE
V0.1建议 忘记密码页面增加一个 返回 按钮

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#126]
路径：忘记密码页面，见附件A
![a](https://cloud.githubusercontent.com/assets/13793913/9622015/9237710e-5160-11e5-8351-50278598b747.jpg)
建议：增加一个 返回 按钮，按钮位置在“确认”按钮右侧，格式与”确认“按钮一致。另外点击”返回“按钮，页面返回到附件B页面（如下图所示）
![b](https://cloud.githubusercontent.com/assets/13793913/9622027/aaa861f8-5160-11e5-9a43-64239ea1bbe0.jpg)

**Comment by dongliu1** [comment]
已完成

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
