### ISSUE TITLE
V0.1用户注册页面 输入内容不符合输入要求时提示正确但不能注册

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#128]
路径：用户注册页面
操作：用户名、昵称输入长度超过50个字符时，密码输入不符合输入要求（比如A123456）时
结果：
1、用户名、昵称和密码输入框后面显示出一个绿色的沟（如下图所示），再点击注册按钮页面无反应。查询数据库用户表，当前用户账号注册不成功
![a](https://cloud.githubusercontent.com/assets/13793913/9622269/48f9fb8a-5163-11e5-9bb3-d838ce2b6b72.jpg)
期望：当用户名、昵称长度和密码输入不符合输入要求时，输入框下方应该显示出对用的输入要求且输入框后面不会出现绿色沟而是提示图标（如下图所示）
![qq 20150902145223](https://cloud.githubusercontent.com/assets/13793913/9624754/47d43d6e-5182-11e5-8d3b-a05832cc1b51.jpg)

**Comment by dongliu1** [comment]
已完成

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
