### ISSUE TITLE
V0.1在昵称输入页面返回到上一页后再回到昵称页面，昵称被默认显示

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#130]
路径：用户注册昵称输入页面
操作：在当前页面中自定义输入昵称（如下图所示）后点击“上一步”按钮接着再点击“下一步”按钮
![a1](https://cloud.githubusercontent.com/assets/13793913/9624053/8aa1591c-517b-11e5-8daf-df4d5ed8fdb2.jpg)
结果：自定义输入的昵称被还原成系统默认显示的昵称，如下图所示
![a2](https://cloud.githubusercontent.com/assets/13793913/9624059/95b2daba-517b-11e5-9044-65766e5ac69e.jpg)
期望：自定义输入昵称后，再点击上一步按钮后再回到昵称页面，自定义的昵称不能被系统修改为默认值

**Comment by dongliu1** [comment]
已完成

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
