### ISSUE TITLE
V0.1建议 用户注册-昵称输入页面点击注册按钮后，页面自动跳转回注册首页

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#131]
路径：注册-昵称输入页面
操作：
1、用户名、密码和手机号按要求正确输入后点击下一步按钮，接着直接点击注册按钮。此时页面提示注册成功
2、现在在不修改昵称的情况下直接点击上一步按钮，再点击下一步按钮，最后点击注册按钮
结果：页面无任何响应和显示
建议：注册成功后页面自动跳转回用户注册首页（即页面右上角有登录按钮的页面）

**Comment by dongliu1** [comment]
已完成

**Comment by dongliu1** [comment]
备注：已更改为注册成功后，跳转到登录页面

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
