### ISSUE TITLE
V0.1用户注册首页 用户名和密码含有中文和非法字符时提示内容不正确

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#133]
路径：用户注册首页
操作：
1、用户名输入格式符合要求的情况下提示内容有误，输入格式如下所示
大写字母、小写字母、_（下划线） + 非法字符（如逗号、分号、括号等）、含中文字符，如下图所示
![a](https://cloud.githubusercontent.com/assets/13793913/9624539/7ecb304a-5180-11e5-9606-a7736fb8fd84.jpg)
![a2](https://cloud.githubusercontent.com/assets/13793913/9624550/9676191c-5180-11e5-89c6-6757b05c7ed0.jpg)
2、密码输入为a_d_1_d（完全符合输入提示要求：使用至少一个小写字母，一个数字，和七个字符）
结果：
1、用户名输入框下方出现提示内容：用户名必须以字母或“_”开头，如上图所示
2、提示：使用至少一个小写字母，一个数字，和七个字符
期望：
1、用户名：当第一个字符符合输入要求后面的不符合输入要求时，提示内容应该为：用户名不能包含中文字符和非法字符且必须以字母或”_“开头
2、密码：输入提示要求内容应改为：使用至少一个小写字母，一个数字，和七个字符，不能使用非法字符

**Comment by AceBear** [comment]
如果已经修复了,标记一下在哪个commit里修复的

**Comment by bingshe** [comment]
修改了，但是语句稍有变动，请查看66e36d7fd3cabc1bd2a3720bf78aceb9632df2c2

**Comment by bingshe** [comment]
66e36d7fd3cabc1bd2a3720bf78aceb9632df2c2

**Comment by bingshe** [comment]
修改了，但是语句稍有变动，请查看66e36d7fd3cabc1bd2a3720bf78aceb9632df2c2

**Comment by bingshe** [comment]
修改了，但是语句稍有变动，请查看 66e36d7fd3cabc1bd2a3720bf78aceb9632df2c2

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
