### ISSUE TITLE
车辆绑定功能

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#136]
车辆绑定功能：
1.车辆绑定
2.车辆解除绑定
数据库设计见邮件
#33

**Comment by jiangli0509** [comment]
POST  /api/vehicle/{vin}/bind/{uid}   绑定车辆
DELETE /api/vehicle/{vin}/bind/{uid}  解除绑定

**Comment by jiangli0509** [comment]
1.建立关系表实体类
2.用户（User）-关系类 oneToMany
3.车辆（Vehicle）-关系类oneToMany
3.朋友（User）-关系类oneToMany

**Comment by flowweerr** [comment]
车辆绑定注意：用户 ->车辆 1对多的关系 ，入参 用户 id -> 车辆id list

**Comment by flowweerr** [comment]
绑定接口修改一下，将vid 改为 vin 和 tbox_id确定唯一车辆

**Comment by tiandashen** [comment]
b976e52af287998fb198da4055bf109e93d968aa
已完成
