### ISSUE TITLE
V0.1 用户名和手机号输入错误，提示已存在

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#140]
路径：用户注册首页面
操作：用户名输入不符合要求和输入的手机号错误
现象：用户名输入框下方显示用户名已存在，手机号输入框下方显示手机号已存在
![qq 20150902172420](https://cloud.githubusercontent.com/assets/13793913/9627836/6e06dba6-5199-11e5-8413-16e8d5da9c9b.jpg)
![qq 20150902172437](https://cloud.githubusercontent.com/assets/13793913/9627841/74b90ece-5199-11e5-88c6-2579f25a36d9.jpg)
![qq 20150902172538](https://cloud.githubusercontent.com/assets/13793913/9627846/79b31082-5199-11e5-949f-b69c3f02e916.jpg)
期望：输入不符合要求时提示内容不要出现XX已存在！

**Comment by dongliu1** [comment]
最新版本已更改，达到要求。PS：此处错误为最初测试版本时用来学习正则表达式的示例，非正式代码。

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
