### ISSUE TITLE
忘记密码输入不存在的手机号

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#155]
忘记密码页面

如果输入一个不存在,但合法的手机号(手机号存在,但未在我们的数据库中注册)
需要有有失败提示

**Comment by TeemolSparrow** [comment]
直接在前台判断通过手机号是否能查询到用户，查询不到则提示手机号未注册

**Comment by dongliu1** [comment]
已完成，在此基础上，完善了获取焦点时，提示信息消失的功能。
