### ISSUE TITLE
HTML: 框架页面增强

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#159]
+ navbar 只有一个,navbar里的元素通过变量控制显示隐藏,而不是navbar本身
+ navbar 放到ng-view外面,即,所有页面都有一个共享的navbar
+ 国际化"车辆管理" "用户管理"
+ 如果已经登录了,那么关掉整个浏览器,再重新打开,也仍然是已登录状态
+ navbar保持黑色调,不需要变换颜色,container也保持使用container-fluid,不需要变换
+ filter genderType性别,放到一个外部共享的JS文件中,因为其它页面也需要用到
+ 初始化激活菜单,不允许使用 timeout,这是不稳定的写法,直接使用angularjs的变量来控制,而不是使用jquery的写法

**Comment by AceBear** [comment]
初始化激活菜单,不允许使用 timeout,这是不稳定的写法,直接使用angularjs的变量来控制,而不是使用jquery的写法

**Comment by dongliu1** [comment]
已改为ng-class

**Comment by AceBear** [comment]
@dongliu1 直接把PR号或者commit号粘到这里
