### ISSUE TITLE
V0.1 用户注册页面 输入已存在的账号点击下一步按钮，页面不应该发生跳转

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#160]
路径：用户注册页面
操作：用户名输入重复，其他输入框按要求输入，然后点击下一步按钮
结果：当鼠标离开用户名输入框后提示 该用户名已存在 ，再点击下一步按钮页面跳转到昵称显示页面
期望：当用户名输入框下方出现 提示内容时点击下一步按钮，页面不发生跳转

**Comment by dongliu1** [comment]
已完成

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
