### ISSUE TITLE
车辆绑定查询功能

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#161]
1.根据车辆查用户   输入：车辆id 返回：用户 list
2.根据用户查车辆   输入：用户id 返回：车辆 list
3.根据车主查朋友   输入：车主用户id 返回：朋友用户 list
#33

**Comment by jiangli0509** [comment]
1.HTTP GET /api/vehicle/{vin}/user
2.HTTP GET /api/user/{uid}/vheicle
3.HTTP GET /api/user/{uid}/friend
@tiandashen

**Comment by tiandashen** [comment]
已完成
