### ISSUE TITLE
V0.1 用户注册页面 输入重复的手机号注册成功了

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#163]
路径：用户注册页面
操作：输入新的用户名和符合输入要求的密码后再输入已存在的手机号，点击下一步按钮，接着点击注册按钮
结果：注册成功
期望：输入重复的手机号后出现提示 该手机号已存在 时点击下一步按钮页面不能发生跳转

**Comment by dongliu1** [comment]
已在#160完成

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
