### ISSUE TITLE
V0.1 昵称含有中文，在其他页面中文部分显示为？？？

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#164]
路径：用户管理列表页面、用户信息修改页面
操作：用户注册时的昵称含有中文（如下图所示），使用该昵称的用户账号登录进用户管理列表页面和用户信息修改页面

结果：昵称含有中文的部分显示为？？？（如下图所示）

**Comment by AceBear** [comment]
The same as #165
