### ISSUE TITLE
V0.1 昵称含有中文，在其他页面中文部分显示为？？？

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#165]
路径：用户管理列表页面、用户信息修改页面
操作：用户注册时的昵称含有中文（如下图所示），使用该昵称的用户账号登录进用户管理列表页面和用户信息修改页面
![a1](https://cloud.githubusercontent.com/assets/13793913/9711381/b9a6f0c0-5575-11e5-9bc9-0ecbbf161c58.jpg)
结果：昵称含有中文的部分显示为？？？（如下图所示）
![a3](https://cloud.githubusercontent.com/assets/13793913/9711369/a5c743f2-5575-11e5-8f53-0af2983b30ca.jpg)
![a4](https://cloud.githubusercontent.com/assets/13793913/9711377/b3748e92-5575-11e5-8c4f-2c646dd0e04e.jpg)
期望：昵称含有中文时，在系统其它页面能正常显示出昵称的中文部分
备注：数据表中显示的也是？？？

**Comment by AceBear** [comment]
@Septemberwh 诊断问题发生在什么位置,然后转给相关的人员处理

**Comment by dongliu1** [comment]
新版本中并不存在此类问题。ps：此类问题一般为本地数据库编码方式不正确，请检查数据库的编码方式。

**Comment by AceBear** [comment]
我们建数据库都使用UTF8字符集
```SQL
mysql -e 'CREATE DATABASE briair CHARACTER SET = utf8;
```
更换数据库默认字符集程序,看看是否问题依旧?

**Comment by flowweerr** [comment]
找到问题的原因是application.yml里数据里连接的url后面加?characterEncoding=utf8

**Comment by AceBear** [comment]
3359339dacc0fa7effe0f7629b29236930a7789c

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
