### ISSUE TITLE
V0.1 用户管理列表页面和修改用户信息 字段名称不一致

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#167]
路径：用户管理列表和修改用户信息页面
期望：
1、在用户管理列表中“账号”字段名改为“用户名”，与用户注册页面显示保持一致
2、用户管理列表上方的查询区域的“用户名称”字段名改为“昵称”，输入框中的默认内容也应该显示为“昵称”
3、用户管理列表中的“名称”字段名改为“昵称”
4、修改用户信息页面中的“账号”字段名改为“用户名”，"名称”字段名改为“昵称”

**Comment by dongliu1** [comment]
已完成更改

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
