### ISSUE TITLE
HTML: 登录

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#17]
+ 调用 HTTP POST /api/login 进行登录
+ 调用 HTTP GET /api/login 获取自己的登录信息 #18

#13

**Comment by jiangli0509** [comment]
已完成

**Comment by AceBear** [comment]
没有登录效果被观察到

**Comment by AceBear** [comment]
##### **NOTE: #17 提及的API已由 #52 进行了修改**
