### ISSUE TITLE
V0.1 用户注销后使用浏览器返回功能 已注销的用户可以对平台功能进行操作

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#172]
前提：用户已成功登陆进平台系统，比如当前页面为 用户管理列表页面
操作：当前用户点击注销按钮，此时页面跳转到用户注册页面。现在在使用浏览器自带的返回按钮（如下图所示）
![a1](https://cloud.githubusercontent.com/assets/13793913/9712356/a6bb17f0-557c-11e5-9e91-b4b5def7dc46.jpg)
结果：当前已注销成功的用户可以对平台的用户数据进行修改，另外当前页面右上方出现登录输入区域，如下图所示
![a2](https://cloud.githubusercontent.com/assets/13793913/9712359/adcb19dc-557c-11e5-9b7d-86ca50f7e5c7.jpg)
期望：用户注销成功后，不能使用浏览器自带返回功能返回到注销前显示的页面

**Comment by AceBear** [comment]
#55 权限管理完成后,此BUG会得到改善:

后退,仍然可以后退到注销前显示的页面,但无法提交任何操作.

**Comment by wjgao** [comment]
在V0.3版本中，此问题暂未处理，等到权限管理完成后在进行复测

**Comment by wjgao** [comment]
v0.5版本上，此问题已处理，复测通过，现在注销后按照操作返回到上一个页面时无内容显示不可操作。
