### ISSUE TITLE
V0.1 用户注册页面 用户名含有中文提示内容不准确

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#178]
路径：用户注册页面
操作：在“用户名”输入框中输入 a中文 或 _中文
结果：该输入框下方显示提示内容为：用户名必须以字母或“_”开头（如下图所示）
![qq 20150908103646](https://cloud.githubusercontent.com/assets/13793913/9725255/0157a20c-5616-11e5-85f7-ca1eb90f2cda.jpg)
期望：如果 用户名 不能含有中文，那么在输入中文时 提示内容应该为：用户名必须以字母或“_”开头，且不能为中文

**Comment by dongliu1** [comment]
已完成，提示变为“用户名必须以字母或“_”开头，且由字母、数字或下划线组成,长度不超过50”。

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
