### ISSUE TITLE
V0.1 用户注册 用户名和昵称长度超过50个字符点击注册按钮，系统无反应

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#179]
路径：用户注册页面
操作：
1、用户名长度超过50个字符，密码和手机号输入符合要求，昵称默认生成（长度超过50个字符），点击注册按钮；
2、用户名长度超过50个字符，密码和手机号输入符合要求，昵称长度改为50个字符，点击注册按钮；
3、用户名长度为50个字符，密码和手机号输入符合要求，昵称默认生成（长度超过50个字符），点击注册按钮；
结果：点击注册按钮后，系统无任何反应，也无提示内容出现
期望：
1、用户名长度超过50个字符时，用户名输入框下方应出现提示内容为：用户名长度不能超过50个字符，只有当用户名长度小于等于50个字符点击下一步按钮页面才发生跳转
2、昵称长度大于50个字符时也应该在输入框下方出现提示内容为：昵称长度不能超过50个字符，只有当昵称长度小于等于50个字符时点击注册按钮，才会出现注册成功提示内容，且注册成功。

**Comment by dongliu1** [comment]
已完成提示，且完善了用户页面与信息设置页面的提示。

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
