### ISSUE TITLE
车辆绑定功能界面设计

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#180]
1.车主绑定、解绑定 界面 ：选择用户 ，选择车辆，绑定车辆 1对多的关系。解绑定类似

#33

**Comment by AceBear** [comment]
##### 业务流程 :flags: 
1. 系统中存在有一个内置1号组织(华晨汽车).
2. 汽车从生产线下线时,录入车辆基本信息(VIN码,TBOX序列号等等)到系统中,归属于1号组织华晨汽车.
3. (可选)汽车被某个经销商购买后,划拨给经销商(组织)
4. 最终用户购买车辆后,输入匹配的(VIN码,TBOX序列号),绑定车辆,形成车主关系:lock:.
5. 车主可以邀请其他人共享车辆; 其它人可接受或拒绝; 车主可分配权限 (查看数据,远程控制等等)
6. 车主可以取消其他人对车辆的共享
7. 车主可以解绑:unlock:定车主关系

+ 车主只能查看**绑定期间:clock3:**的车辆数据,绑定前产生的数据不可以被查看(涉及二手车买卖的问题,二手车车主不应该能查看前车主的行驶数据)
+ 一辆车同一时间,至多仅能有一个车主, 即不允许绑定已有车主的车辆.

**Comment by AceBear** [comment]
![img_20150908_213347](https://cloud.githubusercontent.com/assets/5030312/9736243/9c850ee8-5672-11e5-97a9-26d0db49807c.jpg)

**Comment by AceBear** [comment]
![img_20150908_213347](https://cloud.githubusercontent.com/assets/5030312/9736353/3b3138be-5673-11e5-8b5e-a089d8ffcc63.jpg)
