### ISSUE TITLE
V0.1 用户信息修改页面 昵称长度超过50个字符修改不成功，但无提示

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#181]
路径：用户信息修改页面
前提：当前昵称长度为50个字符，如下图所示
![a1](https://cloud.githubusercontent.com/assets/13793913/9725868/14fc0cf6-561d-11e5-8dce-fd4eb1830ef6.jpg)
操作：在用户信息修改页面，将昵称长度改为超过50个字符（如下图所示），在点击保存按钮
![a2](https://cloud.githubusercontent.com/assets/13793913/9725880/36787a04-561d-11e5-81f8-b8549630c505.jpg)
结果：昵称修改不成功，还是显示为修改前的值（即50个字符长度的值）
期望：在用户信息修改页面，当昵称的长度超过50个字符时，在昵称输入框下方出现提示内容为昵称长度不能大于50个字符。

**Comment by dongliu1** [comment]
已在 #179 中完成

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
