### ISSUE TITLE
回声服务器用浏览器访问会导致进程退出

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#182]
回声服务器用浏览器访问会导致进程退出,访问方式 http://121.40.157.200:9000/

#73

**Comment by jiangli0509** [comment]
网址打不开 @flowweerr

**Comment by AceBear** [comment]
这个BUG就是说打不开,因为进程直接报错退出了

**Comment by jiangli0509** [comment]
这个我也解决不了  @AceBear  帮忙解决一下
