### ISSUE TITLE
V0.1 用户注册页面 去掉 密码提示内容中的句号

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#184]
路径：用户注册页面
现象：密码提示内容中多个符号，如下图所示
![qq 20150908115914](https://cloud.githubusercontent.com/assets/13793913/9726118/347e91ee-5621-11e5-918d-9ef5ccd574aa.jpg)
期望：去掉这个句号，与其他提示内容保持一致

**Comment by dongliu1** [comment]
已完成修改

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
