### ISSUE TITLE
V0.1 忘记密码 输入已使用过的验证码 点击确认按钮，系统无反应

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#186]
路径：忘记密码页面
前提：某个手机号已成功接收到一条验证码285269，且该验证码已经输入并确认过一次
操作：在忘记密码页面，输入与该条验证码对应的手机号和验证码285269，再点击确认按钮
结果：当前页面无任何反应
期望：输入已使用过的验证码再点击确认按钮，当前页面的验证码输入框下方出现提示内容为：该验证码已过期 的提示

**Comment by AceBear** [comment]
不必提示验证码已过期,直接提示**无效验证码**即可

**Comment by dongliu1** [comment]
已完成提示

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
