### ISSUE TITLE
V0.1 忘记密码页面 不输入验证码也可以重新设置密码

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#187]
路径：忘记密码页面
操作：输入正确的手机号后点击发送按钮，接着直接点击确认按钮
结果：页面跳转到设置新密码页面
期望：不输入验证码不能设置新密码

**Comment by dongliu1** [comment]
已完成，点击会提示验证码不能为空

**Comment by wjgao** [comment]
在V0.3版本上 如此操作页面不会发生跳转，但是不输入验证码点击确认按钮，无提示显示

**Comment by dongliu1** [comment]
此功能确实已写，新版本可用，如图：
![3 hl_ jffjjy0n 6nyx](https://cloud.githubusercontent.com/assets/13448811/9873100/25e0ca6c-5bd0-11e5-885a-773705434636.png)

**Comment by wjgao** [comment]
在V0.4版本上复测，此问题已处理，复测通过，关闭
