### ISSUE TITLE
V0.1 忘记密码页面不输入验证码点击确认按钮，系统无反应

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#188]
路径：忘记密码页面
操作：
1、输入正确的手机号后直接点击确认按钮
2、输入正确的手机号后任意输入验证码（不存在的）后点击确认按钮
结果：当前页面无任何反应
期望：
1、不输入验证码点击确认按钮，当前页面的验证码输入框下方应出现提示内容为 请输入验证码 的提示
2、输入不存在或错误的验证码再点击确认按钮，当前页面的验证码输入框下方应出现提示内容为 验证码输入错误，请重新输入的 提示

**Comment by dongliu1** [comment]
已完成，原理与 #186 #189 相同

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
