### ISSUE TITLE
V0.1 忘记密码页面 输入已过期验证点击确认按钮，页面无反应

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#189]
路径：忘记密码页面
前提：程序中验证码有效期为1分钟
操作：
1、输入与用户名绑定的手机号再点击发送按钮，此时活动验证码（999346）
2、等待5分钟后输入验证码（999346）再点击确认按钮
结果：页面无任何反应
期望：输入失效验证码点击确认按钮后，验证码输入框下方出现提示内容为：验证码已失效，请重新获取 的提示

**Comment by AceBear** [comment]
比对验证码时,会出现2种情况:
1. 和服务器上存储的验证码不匹配, 这时反馈错误: 验证码不正确
2. 没有获取到服务器上的验证码(过期导致), 这时返馈: 验证码已失效, 请重新获取

@Septemberwh 看看,服务器端比对验证码的那个API是谁写的,把此BUG指派给他,等他处理完了,你接着处理客户端的提示文字.

**Comment by dongliu1** [comment]
提示已完成，提示内容与抛出异常内容相同：1,，验证码已过期 。2，验证码错误。

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
