### ISSUE TITLE
V0.1 建议 忘记密码页面点击发送按钮后，发送按钮已经不可继续点击

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#190]
路径：忘记密码页面
操作：输入正确的手机号后点击发送按钮
结果：发送按钮可以不停的点击
建议：
1、输入正确的手机号后点击发送按钮，当手机号输入框下方出现提示 发送成功 的提示时 “发送”按钮被灰化
2、只有当输入验证码并点击确认按钮后页面未发生跳转时，“发送”按钮才恢复为 可点击状态

**Comment by AceBear** [comment]
修订 UserController.sendVerifyToPhone 方法

发送短消息前,先尝试从Verifier中获取验证码

1. 如果已经存在,那么不发送验证码,直接向用户报告错误: 发送间隔不得小于XXX秒(正好是设置的过期时间)
2. 如果不存在,那么执行原来的流程

**Comment by AceBear** [comment]
按钮上来个倒计时吧~~~

**Comment by dongliu1** [comment]
界面已完成更改

**Comment by wjgao** [comment]
在V0.4版本上复测，此问题已处理，复测通过，关闭
