### ISSUE TITLE
V0.1 设置新密码页面 输入的密码一致时点击确认按钮，系统无反应

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#192]
路径：设置新密码页面
操作：
1、输入的新密码和确认密码不一致，点击确认按钮；
2、此时修改新密码或确认密码，以便2个密码输入一致且符合输入要求，点击确认按钮
结果：当前页面无任何反应
期望：页面自动跳转到用户登录主页面

**Comment by dongliu1** [comment]
新版中，此功能可用

**Comment by wjgao** [comment]
此问题在V0.4版本中已处理，复测通过
