### ISSUE TITLE
V0.1 当页面跳转到验证码输入页面时不要出现 手机号不能为空的提示内容

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#193]
路径：用户登录主页面
操作：点击忘记密码按钮
结果：当页面跳转到验证码输入页面时，手机号输入框下方出现 手机号不能为空 的提示内容，如下图所示
![qq 20150908170311](https://cloud.githubusercontent.com/assets/13793913/9730822/acf25b68-564b-11e5-866c-2d7a5e19c207.jpg)
期望：第一次进入到验证码输入页面时，不要出现任何输入提示内容

**Comment by dongliu1** [comment]
已完成此功能

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
