### ISSUE TITLE
HTML: Preservation

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#195]
![preservation](https://cloud.githubusercontent.com/assets/5030312/9731873/4abafebc-5652-11e5-999a-bb4a267ad75c.png)

保存的英语应当是简单的 Save
Preservation 的意思是 保留, 当你预订了餐厅时,餐厅为你保留一张桌子叫preservation

**Comment by dongliu1** [comment]
已完成修改
