### ISSUE TITLE
SQL: 系统内置1号组织

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#197]
+ 在数据库中插入系统内置1号组织"华晨汽车"
+ 在数据库中插入系统内置用户组 "超级管理员"
+ 把admin用户加入到"超级管理员组"中
+ 把ADMIN权限加入到"超级管理员组中"

+ 增加权限枚举值 ImportVehicle 导入汽车
+ 增加权限枚举值 CreateSalesOrg 创建经销商
+ 增加权限枚举值 Read 查看

+ 增加内置用户组"生产线管理员"
+ 把 ImportVehicle & Login 这2个权限加入到"生产线管理员"组中

+ 增加内置用户组"观察员"
+ 把 Read & Login 这2个权限加入到"观察员"组中

参见 #109 组织机构管理 了解更多背景信息

**Comment by bingshe** [comment]
85802b30ad0e7cc5deb9b765ef48fd05c59890e2
