### ISSUE TITLE
V0.1 修改用户信息页面 手机号提示信息显示有问题，见描述

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#199]
路径：用户管理-修改用户信息窗口页面
操作：
1、进入到修改信息窗口页面（如下图中是修改之前的手机号）
![a1](https://cloud.githubusercontent.com/assets/13793913/9752250/7d435ed6-56e0-11e5-8501-fbb628bd3725.jpg)
2、将上图中的手机号改为列表中其他用户的手机号再点击保存按钮，此时窗口中出现提示该手机号已存在，如下图所示
![a2](https://cloud.githubusercontent.com/assets/13793913/9752270/ae9107cc-56e0-11e5-8869-e5fdd0ce8b9d.jpg)
3、现在直接关闭窗口，即点击窗口右上角的X
4、重新进入到该用户的修改信息窗口页面中
结果：重新打开的修改信息窗口页面中，手机号显示的是修改前的数据，但是手机号输入框下方依然显示出 该手机号存在，如下图所示
![a3](https://cloud.githubusercontent.com/assets/13793913/9752302/03a09be2-56e1-11e5-9a69-b9d0ef63e79c.jpg)
期望：当修改信息窗口页面中出现提示信息时，手动关闭窗口再重新打开窗口时，提示信息应该消失

**Comment by dongliu1** [comment]
已完成

**Comment by wjgao** [comment]
在V0.3版本上复测通过，此问题已修复
