### ISSUE TITLE
注册用户API

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#2]
# 注册用户API

+ [UserController.java](https://github.com/HP-Enterprise/BriAir/blob/dev/src/main/java/com/hp/briair/user/UserController.java)中实现方法CreateUser
+ 此方法映射到 HTTP POST /user
+ 方法逻辑: 1.调用 Identify.CreatePassword为用户创建密码凭证( 参见 #1  ) 2.调用Triclops中的UserRepository保存用户对象.

**Comment by AceBear** [comment]
@Septemberwh 从dev分出一个你自己的分支,工作完成后再合并回dev

**Comment by Septemberwh** [comment]
已完成，提交到dev分支上了。
