### ISSUE TITLE
JAVA:实体类的生成

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#20]
1. 我们应该用某种工具来从数据库生成对应的实体类
2. 这种工具不应依赖于任何一种开发IDE(IDEA 或 Eclipse)
3. 生成过程可以被gradle集成

请查看 #13 了解更多背景信息

**Comment by jack-luj** [comment]
已完成初步版本，基于开源项目 https://github.com/badqiu/rapid-framework 。
修改后代码已提交，位于https://github.com/jack-luj/rapid-framework.git 具体的Generator目录在 /rapid-framework/generator 下

**Comment by AceBear** [comment]
挂起. 已可以生成实体类,但要配合我们的项目实际运作,还需要更多工作.
当前暂时没有时间进行详细配置
待有空时重启
