### ISSUE TITLE
V0.1 用户管理页面 用户ID输入非数字 查询功能无效

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#201]
路径：用户管理页面
操作：用户ID输入非数字（比如输入e、中文等）或非整数后，点击查询按钮
结果：页面无反应，如下图所示
![z1](https://cloud.githubusercontent.com/assets/13793913/9753074/dcd52636-56ea-11e5-90ae-2cc08d1ebf71.jpg)
期望：输入列表中不存在的用户ID再点击查询按钮，列表中应该不显示任何内容，功能如下图所示
![z2](https://cloud.githubusercontent.com/assets/13793913/9753091/006f1f16-56eb-11e5-9ec7-0e235142b507.jpg)

**Comment by dongliu1** [comment]
已完成

**Comment by wjgao** [comment]
在V0.3版本上复测通过，问题已修复
