### ISSUE TITLE
HTTP: /user -> /api/user

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#21]
为了规范RESTFUL API URL
我们把所有API都以 /api 为前缀URL

+ 请把UserController.java文件中的2个请求修改为 /api 前缀
```
HTTP GET /user      ->  HTTP GET /api/user
HTTP POST /user    ->  HTTP POST /api/user
```

+ 同步修改HTML前台页面中使用到这2个API的位置

请参阅 #13 查看任务背景信息

**Comment by jiangli0509** [comment]
已完成，并merge到了dev。
