### ISSUE TITLE
SQL:车友群

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#210]
1.车友群表：
id --主键
name  --群名称
descript  --群描述
available --是否可用 0 失效 1 可用
2.群与成员关系表：
id  --主键
gid --群id
uid --用户id
level  --成员级别 0 普通 1.管理员 2 群主 扩展字段
available --是否可用 0 失效 1 可用
#211

**Comment by jiangli0509** [comment]
基于dev-driversgroup branch

**Comment by flowweerr** [comment]
不需要建表，用组织管理即可
