### ISSUE TITLE
组织管理(车友群)-获取所有群列表

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#213]
获取所有群列表
输入输出类似用户、车辆即可
#211

**Comment by jiangli0509** [comment]
HTTP GET api/driversgroup

**Comment by AceBear** [comment]
增强 查询ORG的接口,使用特定的查询过滤器即可
HTTP GET /api/org?typeKey={typeKey}

**Comment by tiandashen** [comment]
已完成
