### ISSUE TITLE
组织管理(车友群)-创建群

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#215]
创建群
#211

**Comment by jiangli0509** [comment]
HTTP POST api/driversgroup

**Comment by AceBear** [comment]
修改一下javadoc, 说明typeKey可能取哪些值,分别代表什么意义

**Comment by tiandashen** [comment]
9194744c8274ebdf44970a8de0e683160c6afbe5
d6af811d22a5de61d2c0a53f82d7b6a14a6778e9
已完成
