### ISSUE TITLE
组织管理(车友群)-从群成员中删除成员

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#221]
从群成员中删除成员
#211

**Comment by AceBear** [comment]
HTTP DELET /api/org/{oid}/user/{uid}

**Comment by tiandashen** [comment]
e8f47fc5e04f9bfba56ea93422dbd46d8783b2ce
已完成

**Comment by tiandashen** [comment]
197621019965c6763c19f3d8fa20d909e48d78c9
已完成
