### ISSUE TITLE
JS: 优化多语言支持

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#223]
我们现在无论客户端是什么语言设置,都加载了所有的语言文件

现在修改为,只加载一种需要显示的语言文件

提示:
navigator.language 决定了浏览器的语言设定
依据此设定,只注册一种语言
```
$translateProvider.registerAvailableLanguageKeys(['en', 'zh'], ...);
```

#166 延迟加载

**Comment by jiangli0509** [comment]
#294
