### ISSUE TITLE
SuppressWarnings

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#228]
#### 禁止使用 @SuppressWarnings
这是掩耳盗铃式的行为

https://github.com/HP-Enterprise/BriAir/blob/36ccac43158c96de2891fa486aed745416f09494/src/main/java/com/hp/briair/utils/ListSortUtil.java

**Comment by jiangli0509** [comment]
已完成 2d33e4865ad7d1c138ca41e2679d71a9807089a9
