### ISSUE TITLE
JAVA: logger中文乱码问题

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#229]
我们使用的日志输出会使中文出现乱码
研究一下,使其能正确输出中文

[Application.java#L29-L30](https://github.com/HP-Enterprise/Triclops/blob/e3149f63dfef48ba5df82f19a6e1ed0450b67ae1/src/main/java/com/hp/triclops/Application.java#L29-L30)
```JAVA
this._logger = LoggerFactory.getLogger(Application.class);
this._logger.info("Application is running...");
```

**Comment by AceBear** [comment]
@flowweerr : 有空解决一下这个问题, @jefferyxq 研究了一阵子,未果

**Comment by flowweerr** [comment]
经过广化老师的研究发现，在环境变量里增加JAVA_OPTS=-Dfile.encoding=UTF-8，即可。原理是slf4j读系统默认的编码格式，相当于在java编译的时候，增加了一个-Dfile.encoding=UTF-8的参数。
