### ISSUE TITLE
javadoc

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#232]
E:\InCar\Repo\BriAir\src\main\java\com\hp\briair\OrganizationService\OrgService.java:51: 警告: no @param for sort
    public Page findOrganizationByKeys(Integer currentpage,Integer pagesize,String orderby,Integer sub_oid,Integer sub_recursively,Integer par_oid,Integer par_recursively,Integer uid,Integer u_recursively,String vin,Integer v_recursively,Integer type_key,String sort){
                ^
E:\InCar\Repo\BriAir\src\main\java\com\hp\briair\controller\OrganizationController.java:175: 警告: no @param for sort
    public List orgListByFilter( @RequestParam(value = "currentpage",required = false) Integer currentpage,
                ^

2 warnings

**Comment by bingshe** [comment]
e0f240a2ac9af7afc6f37da0e26da5d7fdfce830 已修改

**Comment by AceBear** [comment]
```
VehicleRepositoryDAO.java:39: 警告: no @param for oid
VehicleRepositoryDAO.java:156: 警告: no @param for oid
```

**Comment by rodbate** [comment]
已修改
