### ISSUE TITLE
用户昵称查询转义字符问题

### ISSUE THREAD

**Issue by dongliu1** [HP-Enterprise/BriAir#239]
路径：用户管理页面
操作：在昵称中输入下划线"_",点击查询。如果输入%7%，点击查询会查询出昵称中带有7的用户。
结果：输入下划线，点击查询，页面无任何变化，经检查，是查询出了所有用户。如下图所示：
1，查询前：
![1](https://cloud.githubusercontent.com/assets/13448811/9805742/4bac89ca-586f-11e5-823a-db220008e3bf.png)
2，查询后：
![2](https://cloud.githubusercontent.com/assets/13448811/9805755/5b64b766-586f-11e5-84a9-cb92f4a4b703.png)

输入%x%（x为任意字符），点击查询，会查询出昵称中包含x（x为任意字符）的用户。如下图所示：
![1](https://cloud.githubusercontent.com/assets/13448811/9805659/5bbf97ea-586e-11e5-8728-2ff484a79e01.png)
![2](https://cloud.githubusercontent.com/assets/13448811/9805663/64f3159e-586e-11e5-9e78-0ea2baa16049.png)
![3](https://cloud.githubusercontent.com/assets/13448811/9805669/78156c12-586e-11e5-9849-bd8b59d01021.png)
![4](https://cloud.githubusercontent.com/assets/13448811/9805671/8ac9e96e-586e-11e5-9d32-8f7d410b7f26.png)
期望：输入的昵称，仅当数据库中都有时才能查询，若含有数据库不包含的字符时，则无法查询。

**Comment by AceBear** [comment]
需要转义字符

参见这里:
http://dev.mysql.com/doc/refman/5.5/en/string-literals.html

**Comment by AceBear** [comment]
Fixed after v0.3

**Comment by AceBear** [comment]
Fixed > v0.3
