### ISSUE TITLE
GFW : 如何查看travis的log

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#241]
##### 1. 当traivs-ci失败时,会对应一个build的id号
-----
![build](https://cloud.githubusercontent.com/assets/5030312/9806050/94b60d14-5872-11e5-8bca-6944c93bacbd.png)

##### 2. 查询此build的详情
-----
HTTP GET https://api.travis-ci.org/builds/79778469
结果中包含一个build的矩阵matrix, 每一个对应一种配置{jdk, os, ...}下的build结果
![matrix](https://cloud.githubusercontent.com/assets/5030312/9806147/9d5cd1c2-5873-11e5-88e6-9f0ad6fe7f0a.png)

##### 3. 查询对应的log日志
-----
HTTP GET https://s3.amazonaws.com/archive.travis-ci.org/jobs/79778470/log.txt

**Comment by AceBear** [comment]
@HP-Enterprise/all 由于travis-ci里有几个JS被GFW, 因此直接点开travis-ci的那个details链接会打不开,只好使用这个曲折的办法

**Comment by lahmyyc** [comment]
已完成，访问方式：
http://localhost:8080/test
