### ISSUE TITLE
v0.3 用户注册成功后，在当前页面停留一段时间后再跳转到用户注册页面

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#248]
路径：用户注册页面
操作：在输入昵称页面点击注册按钮
结果：页面快递跳转到用户注册首页
期望：用户注册成功后，在当前页面出现提示返回还有倒计时多少秒就自动跳转到登录页面
备注：用户资料显示页面-修改密码页面 页面跳转页存在此问题

**Comment by dongliu1** [comment]
已完成五秒后跳转，提示为“注册成功，5秒后跳转”，没有动态时间提示。

**Comment by Septemberwh** [comment]
可以动态的显示5秒倒计时跳转

**Comment by wjgao** [comment]
在V0.4版本上复测，此问题已处理，复测通过，关闭
