### ISSUE TITLE
V0.3 多次点击发送按钮后提示发送短信失败

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#250]
路径：忘记密码-输入验证码页面
操作：
1、输入有效且存在的手机号后点击发送按钮，当页面出现发送成功提示后，再次点击发送按钮
2、此时出现 发送短信失败（如下图所示）的提示，然后关闭浏览器再进行第一步操作
结果：依然提示发送短信失败（必须清理浏览器缓存后才能发送成功）
![qq 20150911144649](https://cloud.githubusercontent.com/assets/13793913/9808739/9ff35cbe-5894-11e5-8d3e-dffa9763b93a.jpg)
期望：点击发送按钮页面出现发送成功的提示后，只有在点击确认按钮后，发送按钮才能再次点击

**Comment by AceBear** [comment]
验证码过期后,也应该可以再次发送

**Comment by wjgao** [comment]
在V0.4版本上复测，此问题已处理，复测通过，关闭
在当前版本中，点击发送按钮后，在一定时间内无法再点击发送按钮，所以此问题已得到解决，关闭
