### ISSUE TITLE
V0.3 忘记密码-验证码页面，验证码提示有误，见描述

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#251]
路径：忘记密码-验证码输入页面
操作：输入已注册的手机号不点击发送按钮的情况下，接着输入不存在的验证码，再点击确认按钮
结果：验证码输入框下方出现 验证码已失效，请重新输入 的提示内容
期望：不点击发送按钮的情况下，输入验证码  验证码提示内容应该为 验证码错误，请获取验证码
备注：失效和错误的区别
1、失效 是已获得验证码 输入存在超时和重复输入
2、错误 是输入错误和验证码不存在

**Comment by AceBear** [comment]
按当前的实现机制,区分不了"已过期" VS "尚未发送验证码" 这2种情况
因此,此BUG暂不修复
