### ISSUE TITLE
V0.3 忘记密码-验证码页面 点击返回按钮，手机号和验证码应该被清空

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#253]
路径：忘记密码-验证码输入页面
操作：输入手机号和验证码后点击返回按钮，再重新返回到验证码输入页面
结果：手机号和验证码还显示在输入框中
期望：点击返回按钮，跳转到其他页面后再回到验证码输入页面，之前的手机号和验证码内容应该被清空

**Comment by dongliu1** [comment]
已完成

**Comment by wjgao** [comment]
在V0.4版本上复测，此问题已处理，复测通过，关闭
