### ISSUE TITLE
V0.3 车辆管理页面中的添加按钮布局不合理

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#254]
路径：车辆管理列表页面
现象：添加按钮位置不合理（如下图所示）
![a](https://cloud.githubusercontent.com/assets/13793913/9809149/6bab9116-5898-11e5-8de4-3ae8a2c85fc7.jpg)
期望：添加按钮放到 查询按钮同行后面对齐

**Comment by AceBear** [comment]
如果需要对得很齐,就得考虑用 TABLE 替代 DIV了

##### 参见
http://v3.bootcss.com/css/#tables

**Comment by dongliu1** [comment]
建议不改

**Comment by wjgao** [comment]
在V0.4版本上复测，此问题已处理，复测通过，关闭
