### ISSUE TITLE
V0.3 用户资料显示页面 将修改按钮名称改为修改资料

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#256]
路径：用户资料显示页面
现象：修改按钮名称不明确，如下图所示
![b](https://cloud.githubusercontent.com/assets/13793913/9809446/c5a278fe-589a-11e5-9790-0d2efffb6dbe.jpg)
期望：将“修改”按钮名称改为“修改资料”

**Comment by dongliu1** [comment]
已完成

**Comment by wjgao** [comment]
在V0.4版本上复测，此问题已处理，复测通过，关闭
