### ISSUE TITLE
V0.3 用户资料-验证页面 提示内容显示问题，见描述

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#257]
路径：用户资料-验证页面
操作：在用户资料显示页面，点击验证按钮
结果：在当前页面中弹出手机验证窗口，验证码输入框下方出现验证码不能为空的提示内容，如下图所示
![a11](https://cloud.githubusercontent.com/assets/13793913/9809641/af6e3350-589c-11e5-9955-856f6a4c4cb2.jpg)
期望：第一次弹出该窗口时，验证码输入框下方不要出现提示内容

**Comment by dongliu1** [comment]
已完成

**Comment by wjgao** [comment]
在V0.4版本上复测，此问题已处理，复测通过，关闭
