### ISSUE TITLE
V0.3 车辆管理 添加/修改页面 输入不符合要求时，点击保存按钮，系统无反应

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#263]
路径：车辆管理 添加/修改页面
操作：车架号大于50个字符，厂家、型号大于100个字符，排量大于20个字符，车牌号大于10个字符 后点击保存按钮
结果：系统无任何反应，页面无提示内容出现
期望：当输入不符合要求时，应该在对应输入框下方出现提示内容

**Comment by dongliu1** [comment]
已完成

**Comment by wjgao** [comment]
在V0.4版本中，
1、车辆新增/修改页面中，TBOX输入长度未做验证（最长为50个字符），当输入符合输入长度的车架号和超过50个字符的TBOX后点击保存按钮，系统无反应（TOMCAT报错）

**Comment by wjgao** [comment]
在V0.4版本上复测，此问题已处理，复测通过，关闭
