### ISSUE TITLE
V0.3 车辆管理 新增成功后，数据表中的时间显示为NULL

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#264]
路径：车辆管理列表页面
操作：添加一个车辆信息，只输入车架号然后点击保存按钮，如下图所示
![a1](https://cloud.githubusercontent.com/assets/13793913/9811569/bc80c96e-58aa-11e5-945e-f1d0fdbb003c.jpg)
结果：车辆管理列表中显示出添加的车辆信息，时间为系统默认时间，如下图所示
![a2](https://cloud.githubusercontent.com/assets/13793913/9811593/da27dfb6-58aa-11e5-89e4-94ca87680460.jpg)
此时查询数据表，发现日期段显示为NULL，如下图所示
![a3](https://cloud.githubusercontent.com/assets/13793913/9811615/f5a5b38a-58aa-11e5-9e49-6501355c981d.jpg)

**Comment by jiangli0509** [comment]
@Septemberwh 这个是不是已经修复了？

**Comment by AceBear** [comment]
@jiangli0509 关于如何再见的详情,可以直接去问 @wjgao

**Comment by jiangli0509** [comment]
#285

**Comment by wjgao** [comment]
在V0.4版本上复测，此问题已处理，复测通过，关闭
