### ISSUE TITLE
登录后的title样式变化：将jquery的方法改为angularjs的方法

### ISSUE THREAD

**Issue by Septemberwh** [HP-Enterprise/BriAir#265]
点击后的样式，在刷新后也要保留在页面：
![qq 20150911173736](https://cloud.githubusercontent.com/assets/9412495/9811772/d72bb3cc-58ab-11e5-84af-7c30b6717ce1.png)

**Comment by TeemolSparrow** [comment]
#159  @Septemberwh  已经做完了
