### ISSUE TITLE
V0.3 建议 车辆管理 添加/修改页面  日期输入框后面增加日期输入格式样式

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#266]
路径：车辆管理-添加/修改页面
操作：日期输入框输入不规则的日期，比如输入 20050101,200511
结果：添加成功，列表中该条数据的日期显示的是系统默认日期或者不是系统默认时间但是个正确日期
建议：添加/修改页面  日期输入框后面增加日期输入格式样式，比如 2005-01-01 如果输入的不符合要求则不能添加/修改成功，且在日期输入框下方出现提示 日期格式输入有误，请重新输入 的提示内容

**Comment by dongliu1** [comment]
已完成，未验证

**Comment by wjgao** [comment]
在V0.4版本上复测，此问题已处理，复测通过，关闭
