### ISSUE TITLE
V0.3 车辆管理-添加/修改页面 系统未对日期输入内容进行验证

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#267]
路径：车辆管理-添加/修改页面
操作：在添加/修改页面 输入不存在的车架号后，在日期输入框中输入纯数字字符串，比如3333300909，如下图所示
![a1](https://cloud.githubusercontent.com/assets/13793913/9812192/37aa9ab8-58ae-11e5-827a-8cd2f71710b2.jpg)
结果：添加/修改成功，在列表中该条数据的日期显示不是系统默认日期（默认日期是1970-01-01），如下图所示
![a2](https://cloud.githubusercontent.com/assets/13793913/9812217/593d1fca-58ae-11e5-88a6-63e8c65dc199.jpg)
期望：在添加/修改页面，需要对日期输入格式进行验证

**Comment by rodbate** [comment]
VehicleController ----------createVehicle()?
