### ISSUE TITLE
V0.3 车辆管理 生产日期默认时间查询结果不正确

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#275]
路径：车辆管理列表页面
操作：
1、进入到车辆管理列表页面，生产日期开始时间和结束时间输入框中默认显示一个月的时间段
2、然后直接点击查询按钮
结果：列表中显示的是所有数据，如下图所示
![qq 20150914100436](https://cloud.githubusercontent.com/assets/13793913/9840668/3cb64e6e-5ac8-11e5-864a-099db8f314de.jpg)
期望：
1、如果生产日期有默认时间段显示出来，列表中的数据的生产日期就应该符合默认时间段查询条件
2、建议默认时间段中的结束时间默认显示为系统当前时间，开始时间和结束时间周期以1个月为准

**Comment by dongliu1** [comment]
placeholder只是属性值，不是日期的默认值，日期默认值为空。

**Comment by wjgao** [comment]
在V0.4版本上复测，不是BUG，关闭
