### ISSUE TITLE
根据车辆查询用户、根据车主查询朋友的API集成到查询用户API

### ISSUE THREAD

**Issue by jiangli0509** [HP-Enterprise/BriAir#276]
HTTP GET /api/vehicle/{vid}/user、HTTP GET /api/vehicle/{pid}/friend——》HTTP GET /api/user
开新分支

**Comment by wangh2015** [comment]
35d2fe87272f2b66cda3110149d4b7deb8441cd0   #276 #277共用 dev-#276分支
