### ISSUE TITLE
根据用户查询车辆API集成到车辆查询API

### ISSUE THREAD

**Issue by jiangli0509** [HP-Enterprise/BriAir#277]
HTTP GET /api/vehicle/{uid}/vehicle ——》 HTTP GET /api/vehicle
和上个issues一个分支

**Comment by wangh2015** [comment]
35d2fe87272f2b66cda3110149d4b7deb8441cd0

**Comment by wangh2015** [comment]
1c27214a7c12404a559e6c162abaccd4549a7503 #277 测试了 一号或者2号组织管理员 查询车辆，以及和前台传的参数进行联合查询
