### ISSUE TITLE
V0.3 车辆管理 修改页面去掉生产日期保存显示的不是默认时间

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#279]
路径：车辆管理-车辆修改页面
操作：清空生产日期后点击保存按钮
结果：在列表中该车辆的生产日期还是为清空前的值，另外再次进入到该车辆修改页面，生产日期也未更改
期望：当生产日期被清空且保存成功后在列表页面和重新进入到修改页面，生产日期默认显示为1970-01-01

**Comment by dongliu1** [comment]
已完成

**Comment by wjgao** [comment]
在V0.4版本上复测，此问题已处理，复测通过，关闭
