### ISSUE TITLE
V0.3 基本资料-修改密码 去掉原始密码下方出现的提示信息

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#282]
路径：用户基本资料-修改密码
操作：在原始密码输入框中输入数据
现象：原始密码输入框下方出现 至少使用七个字符，且包含至少一个小写字母和一个数字,不能使用非法字符 的提示信息
期望：在输入原始密码的过程中不需要显示该条输入要求信息

**Comment by dongliu1** [comment]
已完成

**Comment by wjgao** [comment]
在V0.4版本上复测，此问题已处理，复测通过，关闭
