### ISSUE TITLE
V0.3 基本资料-验证 手机验证问题，见描述

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#283]
修改路径：用户 基本资料-验证页面
前提：当前手机号处于 未验证状态（如下图所示）
![a1](https://cloud.githubusercontent.com/assets/13793913/9843757/d1ae3474-5aef-11e5-9907-bf822dc8d54b.jpg)
操作：
1、进入到验证页面，获取验证码并在1分钟内输入验证码再点击确认按钮；
2、页面返回到基本资料展示页面，并且该手机号显示为已验证，如下图所示；
![a2](https://cloud.githubusercontent.com/assets/13793913/9843800/3e4c2dde-5af0-11e5-808c-f905f79bca47.jpg)
3、现在进入到用户管理列表页面并修改该用户手机号且保存成功，如下图所示；
![a3](https://cloud.githubusercontent.com/assets/13793913/9843883/04fc0a26-5af1-11e5-9b27-01dd1572b60f.jpg)
4、现在再点击页面右上角的用户名进入到基本资料页面
结果：修改后的手机号显示为 已验证，如下图所示
![a4](https://cloud.githubusercontent.com/assets/13793913/9843894/26b52d32-5af1-11e5-9701-b401d42ad126.jpg)
期望：在用户管理模块修改了手机号再进入到用户基本资料页面，该手机号应该显示为 未验证

**Comment by Septemberwh** [comment]
已完成

**Comment by wjgao** [comment]
在V0.4版本上复测，此问题已处理，复测通过，关闭
