### ISSUE TITLE
V0.3 基本资料-手机号验证 手机号与验证码不对应的情况下可以验证通过

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#287]
前提：当前手机号为 未验证状态，如下图所示
![a1](https://cloud.githubusercontent.com/assets/13793913/9844056/bdd7d600-5af2-11e5-8770-764d73f11748.jpg)
操作（以下操作在1分钟内完成，验证码有效时间内均可）：
1、进入到手机号验证页面，获取验证码（如下图所示）并在1分钟内输入正确的待验证后点击确认按钮
![a2](https://cloud.githubusercontent.com/assets/13793913/9844180/b25fcd36-5af3-11e5-88be-cf22dae319b7.jpg)
2、此时该手机号显示为已验证，如下图所示
![a3](https://cloud.githubusercontent.com/assets/13793913/9844094/fb6d4c02-5af2-11e5-970a-6887fdb0c20a.jpg)
3、接着在当前页面点击修改按钮并重新编辑手机号并点击保存按钮，页面跳转后基本资料页面，此时手机号已变更且为 未验证码，如下图所示
![a4](https://cloud.githubusercontent.com/assets/13793913/9844109/251ca728-5af3-11e5-9f46-b166f046eb0c.jpg)
4、现在再点击验证按钮
结果：
1-1、在当前页面弹出手机验证窗口，手机号未修改后的，验证码自动显示在验证码输入框中且验证码修改之前手机号获得的（如下图所示），此时再点击确认按钮
![a5](https://cloud.githubusercontent.com/assets/13793913/9844194/ce062a58-5af3-11e5-99b3-4c8011568b49.jpg)
1-2、窗口关闭，此时新手机号右侧显示 已验证，如下图所示
![a6](https://cloud.githubusercontent.com/assets/13793913/9844346/03cdc24e-5af5-11e5-8376-9a4a0adf42f6.jpg)
期望：点击验证按钮后，之前输入的验证码不要显示出来，另外手机号显示框下方不要显示出绿色字体的提示发送短信成功的字符串

**Comment by Septemberwh** [comment]
已完成

**Comment by wjgao** [comment]
在V0.4版本上复测，此问题已处理，复测通过，关闭
