### ISSUE TITLE
登录页面

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#3]
+ 搭建基本的网站页面
+ 直接使用 bootstrape (参考这个 [http://v3.bootcss.com/examples/jumbotron](http://v3.bootcss.com/examples/jumbotron) )
+ 公共库使用百度CDN [http://cdn.code.baidu.com/about](http://cdn.code.baidu.com/about)
+ 使用requirejs方式加载JS

**Comment by jiangli0509** [comment]
已完成，已提交到deb分支。

**Comment by jiangli0509** [comment]
改成直接使用bootstrap的那个页面了
