### ISSUE TITLE
诶,英文不堪入目啊

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#307]
![v](https://cloud.githubusercontent.com/assets/5030312/9869853/d6d34bae-5bb9-11e5-84d2-fe468acb78bb.png)

+ Vehicle number 不要翻译, 直接使用VIN的缩写,它是Vehicle Identification Number
+ License plate number 要用 Plate No.   注意,不是No是No.那个点号不能省略,省略是"不"的意思,带个点号表示number, 而license表示驾照, plate no. 表示车牌号
+ Manufacture date, 这个词表示出厂日期,制造日期
+ 生产厂家是 vendor, 不是ER

**Comment by dongliu1** [comment]
已完成更改（英语捉急，见谅。= =）
