### ISSUE TITLE
JAVA: 创建组织成功后,马上创建缺省权限组

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#312]
+ 修改OrganizationController.CreateOrg 在创建组织成功后,创建2个权限组
+ 一个是"Admin"组, 缺省赋给admin权限
+ 一个是"User"组, 缺省赋给login & read权限
+ 如果是组织类型是经销商,那么再给user组赋给"导入汽车权限"权限
+ 权限组里不需要有缺省用户
+ 至少1个单元测试

参阅 #55 权限管理 查看更多背景信息

**Comment by tiandashen** [comment]
ac53391878760af1b529d8f51130f5ef55beed92
已完成

**Comment by jiangli0509** [comment]
@AceBear 至少一个单元测试没完成，一直报415的错误找不到原因
