### ISSUE TITLE
JAVA: 查询用户权限控制

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#316]
修改UserController.GetUser & UserController.list

+ 如果是1号组织的管理员,则不加任何限制
+ 如果是其它组织的管理员,只允许查询组织内的成员
+ 其它用户,只允许进行单用户查询(一定只会返回单个用户信息的查询: 按name, phone, id)
+ 其它用户,如果进行单用户查询,且不是自已时,返回的结果中phone号码末6位用*星号替换

参阅 #55 权限管理 查看更多背景信息

**Comment by tiandashen** [comment]
d6bef1928dfee8a59c880a2d7cac8bf9347081cb
已完成

**Comment by tiandashen** [comment]
bdc3219692bffefa155b4e9349463eafeff2ea97
已完善

**Comment by jiangli0509** [comment]
46346432 已完成
