### ISSUE TITLE
JAVA: 图形验证码

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#320]
创建用户时,提供一个"图形验证码"进行防机器人验证
先进行设计: 需要修改哪些类,新增哪些类

**Comment by jiangli0509** [comment]
设计：
* 在utils下面新增ValidateCode.java验证码生成类

**Comment by jiangli0509** [comment]
前后台完整的使用图形验证码设计：
*  main.html创建用户在昵称栏下方加一栏验证码
*  mainCtrl.js的nextStep方法里加入发送获取验证码的request
* LoginController.java里面加入生成图片验证码API，返回图片路径，验证码存入redis（30秒过期）
* ValidateCode.java里面提供图片验证码
* mainCtrl.js的toRegister加入判断验证码是否输入正确
* LoginController.java里面加入判断验证码是否正确API

**Comment by AceBear** [comment]
这个完成了,直接CLOSE即可,无须转我了,除非有其它意外发生
