### ISSUE TITLE
JAVA: 修改用户的权限控制

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#321]
修改 Controller.ModifyUser

+ 允许用户自己修改自己的信息
+ 允许组织中且拥有admin权限的用户修改同组织中其它用户的权限(修改用户所在的权限组,分配权限组的权限)

**Comment by tiandashen** [comment]
0e19b5f5b1a2f0cb92752e62649f32dcc7bf4731
第一个任务完成
“允许组织中且拥有admin权限的用户修改同组织中其它用户的权限”  这个任务在等待广华

**Comment by Liujingguo91year** [comment]
41e5624a
已完成任务
允许用户自己修改自己的信息
允许组织中且拥有admin权限的用户修改同组织中其它用户的权限(修改用户所在的权限组,分配权限组的权限)
