### ISSUE TITLE
JAVA：修改查询车辆信息的权限控制

### ISSUE THREAD

**Issue by jefferyxq** [HP-Enterprise/BriAir#326]
修改Controller.getVehicle、Controller.list

+ 如果是1号组织的管理员则不加任何限制，可以查询任何组织下的车辆信息
+ 如果是其他组织的管理员只能查询所属组织下的车辆信息
+ 其他用户，只能查询与该车主绑定的车辆信息

**Comment by wangh2015** [comment]
33c6397a8abc7b7c3a0b76b6dfa1830ea9cd76a3 .getVehicle（完成）、Controller.list（完成是车主本人和查看所有车辆权限）

**Comment by wangh2015** [comment]
a0352db85b8086e34327643319417dd8fe3fbbda   分支dev-vehicleList-#277

**Comment by jiangli0509** [comment]
BUG:
1.存储过程没有写成sql文件
2.在没有登录直接查询一辆车报空指针错误
3.多个组织的管理员没有查出任何数据

**Comment by jiangli0509** [comment]
已测试完成
