### ISSUE TITLE
JAVA：修改更新车辆信息的权限控制

### ISSUE THREAD

**Issue by jefferyxq** [HP-Enterprise/BriAir#329]
修改Controller.modifyVehicle

+ 如果是1号组织的管理员则不加任何限制，可以修改任何组织下的车辆的全部信息
+ 如果是其他组织的管理员只能修改所属组织下的车辆的全部信息
+ 其他用户，如果是车主，只能修改与该车主绑定车辆的部分信息，信息包括车牌号
+ 其他用户，如果是非车主，不能修改车辆信息

**Comment by wangh2015** [comment]
f56985186687ae63d84537553ac5078d4f1955cd

**Comment by wangh2015** [comment]
74842ef5ab5ffd2f6e13dd0b6767b1b6b9f01cc3

**Comment by wangh2015** [comment]
d3c09c7e33945d8fe58e2b44412709210bb173dc

**Comment by wangh2015** [comment]
dd8ec2ca8d8fccd9b4a9f955f55a71e699dbcc48

**Comment by wangh2015** [comment]
58f87460573a576b3fb5e5b478fd6fb399071c0b
