### ISSUE TITLE
JAVA：在AuthorityEnum类中添加车辆信息更新权限

### ISSUE THREAD

**Issue by jefferyxq** [HP-Enterprise/BriAir#330]
在AuthorityEnum类中，添加一个枚举项——UpdateVehicleInfo("更新汽车信息权限")，
拥有该项权限的用户组可修改车辆的车牌信息。

**Comment by wangh2015** [comment]
f56985186687ae63d84537553ac5078d4f1955cd

**Comment by wangh2015** [comment]
74842ef5ab5ffd2f6e13dd0b6767b1b6b9f01cc3

**Comment by wangh2015** [comment]
d3c09c7e33945d8fe58e2b44412709210bb173dc

**Comment by wangh2015** [comment]
dd8ec2ca8d8fccd9b4a9f955f55a71e699dbcc48
