### ISSUE TITLE
推送服务

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#332]
+ 客户端登录后向服务器注册自己的设备标识符(devid)
+ 服务器向(uid+devid)推送消息后, 已登录的客户端应当能够迅速收到消息
+ 服务器向(uid+devid)推送消息后, 未登录的客户端应不能收到消息
+ 服务器向(uid+devid)推送消息后, 未登录的客户端, 登录后应能迅速收到消息
+ 服务器向(uid+devid)推送消息前, 如果发现此客户端已经N小时没有收取消息,则清理掉此(uid+devid)
+ 一个用户,允许对应多个devid(比如,一个手机,一个PAD)

**Comment by AceBear** [comment]
@jefferyxq 确认一下,这些功能是否都实现了

**Comment by AceBear** [comment]
@jefferyxq 的这个转给你继续处理吧

**Comment by flowweerr** [comment]
消息缓存没有在代码里实现，可以依赖客户端注册方式实现
