### ISSUE TITLE
JAVA: 新增车辆后,车辆归属给组织

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#334]
修订 VehicleController.createVehicle 方法

+ 当车辆创建成功后,把车辆归属到1号组织
+ 在POST BODY中,增加一个oid参数, 在归属到1号组织成功后,把车也归属到oid指定的组织中, oid指定的组织必须存在

**Comment by Septemberwh** [comment]
其他组已经做了
