### ISSUE TITLE
JAVA：修改更新组织信息的权限控制

### ISSUE THREAD

**Issue by jefferyxq** [HP-Enterprise/BriAir#341]
修改OrganizationController.updateOrganization

+ 如果是组织中的管理员，则允许修改该组织及该组织下的子组织信息，可修改信息包括：组织名称，组织简码， 组织类型，描述，是否可用，不允许跨组织修改子组织信息

**Comment by Liujingguo91year** [comment]
已完成 41e5624

**Comment by tiandashen** [comment]
OrganizationCintroller中：
![error](https://cloud.githubusercontent.com/assets/13448617/10156942/76fcfe82-66b8-11e5-83bf-d404cbbcb86a.png)
getOrganization()得到的是这个组织的子组织的集合，那么之后的包不包含就没有意义了；
organizationShow是用来获取前端传过来的参数的，跟Organization类型完全不一样，所以不会存在包含；

**Comment by jiangli0509** [comment]
![image](https://cloud.githubusercontent.com/assets/5874912/10416111/fe97317a-7039-11e5-876b-fddcc449b4ad.png)
这个是什么意思？

**Comment by AceBear** [comment]
@jiangli0509 

如果你有代码要引用,优先使用代码区块
```JAVA
if(i == parOrg.size()){        //如果都是不是管理员
    throw new HttpException(HttpStatus.BAD_REQUEST, requestContext.getMessage("unauthorized"));
}
```
可以再附上代码的引用位置
[OrganizationController.java#L159-L161](https://github.com/HP-Enterprise/BriAir/blob/9d0167648b6989f5cf995909e5b27d6b54051c03/src/main/java/com/hp/briair/controller/OrganizationController.java#L159-L161)
