### ISSUE TITLE
JAVA：修改删除组织的权限控制

### ISSUE THREAD

**Issue by jefferyxq** [HP-Enterprise/BriAir#343]
修改OrganizationController.removeOrganization

+ 如果是组织中的管理员，则允许删除其管理组织下的子组织；如子组织下还有子组织，则不能删除，同理依此类推。只有当要删除的目标组织下没有子组织时，才允许被删除；如要删除的目标组织下有用户存在，则将用户自动归属到默认“未分组”组织中，该组的用户权限仅为登录权限

**Comment by wangh2015** [comment]
6acebe66a2b4a5e31e1a345d954404235d993a0a
