### ISSUE TITLE
JAVA：修改查询某个组织详细信息的权限控制

### ISSUE THREAD

**Issue by jefferyxq** [HP-Enterprise/BriAir#344]
修改OrganizationController.findByGid

+ 如果是组织中的管理员，则允许查看其管理组织下的所有组织信息
+ 含有READ权限,亦允许查看组织信息

**Comment by wangh2015** [comment]
31a64fdde64b3361f8a50b0ab1fd0478ad28eb22 #344 已测试

**Comment by jiangli0509** [comment]
1.管理员能查询本组织以及所有子组织的信息 
  目前只满足查询本组织
2.有READ权限的管理员能查询本组织以及所有子组织的信息
  均未实现
@wangh2015

**Comment by wangh2015** [comment]
65ab255e140b97d9d8c6c5319827d1d1c2d2a506

**Comment by jiangli0509** [comment]
已完成
