### ISSUE TITLE
HTTP    DELETE  /api/org/{oid} 删除组织

### ISSUE THREAD

**Issue by jiangli0509** [HP-Enterprise/BriAir#348]
@AceBear 你是不是望了分配这个issues？

**Comment by jiangli0509** [comment]
删除该组织，以及解除和子组织的关系

**Comment by tiandashen** [comment]
3dbf15059f9081e4606073617858d980d8f396f4

**Comment by AceBear** [comment]
删除组织的逻辑非常复杂.我本打算留到下周再写

**Comment by AceBear** [comment]
@tiandashen  先按简单的做,以后再改进: **如果存在子组织,那么此组织不能被删除**
