### ISSUE TITLE
微信页面重新对接问题

### ISSUE THREAD

**Issue by Septemberwh** [HP-Enterprise/BriAir#350]

**Comment by Septemberwh** [comment]
服务预约中，新页面中没有此代码，如下图：
![qq 20150918100044](https://cloud.githubusercontent.com/assets/9412495/9950399/bb9ec91e-5dec-11e5-96a9-92504e4f2a5e.png)

**Comment by Septemberwh** [comment]
信息一览中，没有加载图标的代码

**Comment by Septemberwh** [comment]
车辆报警中，新代码中没有
![qq 20150918104313](https://cloud.githubusercontent.com/assets/9412495/9950859/16f5bc14-5df2-11e5-8841-d92c0d40e5f2.png)

**Comment by Septemberwh** [comment]
活动详情中，不仅有活动的详情页面，还有如果没有参加活动可以报名的页面；此页面也无显示tips的提示框如（信息一览）

**Comment by dongliu1** [comment]
车型介绍中缺少一行代码，如下：
![1](https://cloud.githubusercontent.com/assets/13448811/9984752/1ccc2ed8-6050-11e5-85b5-4696a1ca45b8.png)
且缺少无数据提示代码

**Comment by dongliu1** [comment]
加油站页面，缺少一行ng-include代码
