### ISSUE TITLE
JAVA：修改创建、删除权限组的权限控制

### ISSUE THREAD

**Issue by jefferyxq** [HP-Enterprise/BriAir#357]
修改AuthorityController.createGroup、AuthorityController.delGroup

+ 如果是管理员则允许创建、删除任何权限组

**Comment by Liujingguo91year** [comment]
已完成  7824127a5bac97ce839419c483e9a284e77f01a0

**Comment by jiangli0509** [comment]
在这个分支上没有看到你写的权限控制代码！

**Comment by tiandashen** [comment]
已修改，并完成测试
47fae0adce9190ad7db01fcaf5483e973ecd8dba
