### ISSUE TITLE
V0.4 组织管理-新增页面中的按钮格式不统一

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#369]
路径：组织管理-新增页面
现象：新增页面中的“保存”和“取消”按钮样式（如下图所示）与其他模块页面中的不一致
![a1](https://cloud.githubusercontent.com/assets/13793913/10010592/048c3fb8-6120-11e5-8c05-b74ba97276c8.jpg)
期望：“保存”和“取消”按钮的统一样式见下图所示
![a2](https://cloud.githubusercontent.com/assets/13793913/10010601/2a3131b0-6120-11e5-8157-b5498ffaa873.jpg)
备注：请检查下修改页面中的这2个按钮样式是否存在同样的问题

**Comment by AceBear** [comment]
@TeemolSparrow @Septemberwh 协商一下,使用统一的风格

**Comment by wjgao** [comment]
v0.5版本上，此问题已处理，复测通过，关闭
