### ISSUE TITLE
V0.4 我的爱车新增页面输入内容后点击保存按钮，系统无任何反应

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#370]
路径：我的爱车
操作：输入“车辆管理”列表中不存在的VIN数据和TBOX数据后点击保存按钮
结果：当前新增窗口页面无任何反应
备注：TOMCAT报错：输入的信息不存在
期望：在“我的爱车”绑定车辆“窗口中输入不存在的VIN和TBOX数据且点击保存按钮后，在”VIN“和”TBOX“输入框下方显示出：VIN输入错误，请重新输入 和 TBOX输入错误，请重新输入 的提示内容

**Comment by dongliu1** [comment]
已完成修改

**Comment by wjgao** [comment]
v0.5版本上，此问题已处理，复测通过，关闭
