### ISSUE TITLE
V0.4 我的爱车新增2个一样的车辆数据后再点击解除绑定按钮，系统无反应

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#371]
路径：我的爱车模块页面
前提：已成功绑定一个VIN为 CH001 ，TBOX为TBOX001的车辆
操作：
1、点击绑定车辆按钮在弹出的窗口中输入VIN为 CH001 ，TBOX为TBOX001 数据后点击保存按钮
2、此时再点击2条相同车辆数据后面的”解除绑定“按钮
结果：系统无任何反应，且未解除绑定
期望：
1、功能上：同一个用户账号不能重复绑定已被绑定的车辆（VIN相同的）
2、提示信息： 该车辆已被绑定，不能重复绑定，请重新输入

**Comment by AceBear** [comment]
已被绑定的车辆,不允许再被其它用户绑定
@TeemolSparrow  确认一下,是否API端没有报告错误,如果是API的问题,写一个单元测试,暴露此问题(注意,只需要写单元测试,不需要修复),然后PR给我

如果不是API问题,直接修复

**Comment by rodbate** [comment]
已修改 #385

**Comment by wjgao** [comment]
v0.5版本上，此问题已处理，复测通过，关闭
一辆车只能被一个人绑定
