### ISSUE TITLE
V0.4 组织管理页面中的“添加”按钮样式与其他模块不一致

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#373]
路径：组织管理列表页面
现象：“添加”按钮样式与其他页面不一致，组织管理列表页面的按钮样式如下图所示
![a2](https://cloud.githubusercontent.com/assets/13793913/10011840/20e3f738-6133-11e5-9f2c-3873e01489f7.jpg)
期望：“添加”按钮的样式请保持统一，正确的样式如下图所示
![a1](https://cloud.githubusercontent.com/assets/13793913/10011850/36528102-6133-11e5-9e8a-15bd2a4a970b.jpg)

**Comment by AceBear** [comment]
@TeemolSparrow @Septemberwh 协商一下,统一风格

**Comment by wjgao** [comment]
v0.5版本上，此问题已处理，复测通过，关闭
