### ISSUE TITLE
V0.4 车辆管理新增/修改页面 TBOX重复输入无法保存且无提示信息出现

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#374]
路径：车辆管理-新增/修改页面
前提：车辆列表中已存在至少一条车辆数据
操作：在新增/修改页面，TBOX输入重复后点击保存按钮
结果：系统无任何反应，新增/修改窗口未显示，TOMCAT报错
期望：TBOX数据必须做唯一验证

**Comment by wjgao** [comment]
v0.5版本上，此问题未处理，问题依然存在

**Comment by wjgao** [comment]
在V0.5版本中此问题无法复测，不能新增车辆，等修改完 无法新增车辆的问题后再复测此问题

**Comment by TeemolSparrow** [comment]
此问题已修复，请在下个版本中验证

**Comment by wjgao** [comment]
在V0.8版本上此问题依然存在

**Comment by TeemolSparrow** [comment]
修改车辆信息时，也要对TBOX数据经行唯一性验证，请顺带修改此问题

**Comment by wjgao** [comment]
在V0.9版本上该BUG已处理，复测通过，关闭
