### ISSUE TITLE
V0.4 车辆管理新增时输入重复的车架号，系统无提示信息显示

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#375]
路径：车辆管理
前提：列表中至少有一条数据（车架号为CH001，TBOX为TBOX001）
操作：首页进入到车辆管理列表页面，点击“添加”按钮，然后输入车架号为CH001，TBOXW为TBOX002点击保存按钮
结果：当前添加窗口无任何反应，TOMCAT报错
备注：按照以下操作，此BUG不会出现，请注意
前提：车辆列表中存在CH001和CH002两条车辆数据
操作：
1、首先进入到CH001车辆修改窗口中，重新输入车架号改为CH002，此时当前窗口会出现“该车架号已存在”的提示信息；
2、此时关闭当前修改车辆窗口；
3、点击“添加”按钮；
4、输入车架号为CH002
结果：车架号输入框下方出现“该车架号已存在”的提示内容
期望：不管进行何种操作，输入重复已存在的车架号后，车架号输入框下方会出现“该车架号已存在”的提示内容

**Comment by wjgao** [comment]
V0.5版本中，无法新增第二条车辆数据，所以此问题暂时无法复测，等到新BUG修复后复测

**Comment by TeemolSparrow** [comment]
问题已修复，请在下个版本中验证

**Comment by wjgao** [comment]
在V0.8版本上此问题已处理，复测通过，关闭
