### ISSUE TITLE
V0.4 我的爱车 多人绑定同一辆车其中一个解绑，所有用户均解绑了

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#376]
路径：我的爱车页面
前提：当前已有至少2个用户绑定了同一台车
操作：其中一个用户解除绑定
结果：另外一个用户也被解除绑定
期望：多人绑定同一台车时，其中一人解除绑定不会影响其他人员继续绑定车辆，至少共享数-1

**Comment by Septemberwh** [comment]
现在所做的都是车主的绑定，并且也没有限定一辆车只能绑定一个车主，所以如果接触绑定，其他绑定次辆车的人都会解除绑定。

**Comment by AceBear** [comment]
限定每台车只能绑定1个车主

**Comment by wjgao** [comment]
v0.5版本上，此问题已处理，复测通过，关闭
一辆车只能绑定一个用户，不能多个用户绑定同一台车
