### ISSUE TITLE
v0.4 绑定车辆成功后无法在车辆管理模块新增车辆

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#377]
路径：车辆管理
前提：车辆管理列表中至少有一条车辆数据
操作：在我的爱车模块成功绑定一条车辆后，再进入到车辆管理列表页面，在添加窗口中输入不重复的车架号和TBOX值后点击保存按钮
结果：添加车辆窗口中无任何提示，点击保存按钮系统无反应，TOMCAT报错
备注：取消绑定也无法新增车辆数据

**Comment by Septemberwh** [comment]
验证之后，没有发现错误，可能原因是tbox页面没有进行验证

**Comment by AceBear** [comment]
写一个能暴露这个问题的单元测试

**Comment by Septemberwh** [comment]
测试类已经写完：VehicleControllerTest.java

**Comment by Septemberwh** [comment]
发现此现象还有一种情况，是因为车牌号是可以为空的，而数据库中t_vehicle表中设置车牌号为 UNIQUE KEY

**Comment by AceBear** [comment]
[V20150820.1__t_vehicle.sql#L14-L15](https://github.com/HP-Enterprise/Triclops/blob/cb827eef9c0e3658c914f8b77122ea3229152bf6/src/main/resources/db/migration/V20150820.1__t_vehicle.sql#L14-L15)

tboxsn & plateNo 上有索引,但不是唯一索引

**Comment by wangh2015** [comment]
解决BUG 已PR 广化

**Comment by wjgao** [comment]
在V0.8版本上此问题已处理，复测通过
