### ISSUE TITLE
V0.4 车辆管理 新增/修改页面 增加TBOX必输验证

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#378]
路径：车辆管理-新增/修改页面
现象：不输入TBOX也能新增/修改车辆信息，但无法在我的爱车模块绑定车辆
期望：在车辆管理-新增/修改页面，增加TBOX必输验证

**Comment by dongliu1** [comment]
TBOX不为空，最大长度已验证，唯一性没有验证。此外还出现第一次添加车辆时vin不为空提示没有隐藏、取消添加车辆时无法清空所有数据、vin为空时显示车架号已存在等问题，都已解决。

**Comment by wjgao** [comment]
v0.5版本上，此问题已处理，复测通过，关闭
