### ISSUE TITLE
V0.4 用户基本资料-验证页面，可以多次点击发送按钮，不合理

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#384]
路径：用户基本资料-验证页面
操作：输入正确的手机号后点击发送按钮后，再次点击发送按钮
结果：手机号输入框下方出现 发送短信失败，请重新输入 的提示内容（如下图所示）。实际上第一次点击发送按钮后，手机会收到验证码
![a1](https://cloud.githubusercontent.com/assets/13793913/10015359/48ac63bc-6152-11e5-9218-ec6d62d90fd8.jpg)
期望：当点击了发送按钮后，在一段时间内不允许点击发送按钮，增加一个倒计时功能（如下图所示）
![a2](https://cloud.githubusercontent.com/assets/13793913/10015402/889ea7c8-6152-11e5-84d8-4e0d8ff2d07b.jpg)

**Comment by Septemberwh** [comment]
已完成

**Comment by wjgao** [comment]
v0.5版本上，此问题已处理，复测通过，关闭
