### ISSUE TITLE
V0.4 在用户管理页面修改的手机号，在用户基本资料验证页面 发送提示发送失败

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#386]
路径：用户管理列表页面和用户基本资料-验证页面
操作：
1、先在用户管理列表页面，对某个用户（比如A）的手机号进行修改（输入格式正确未报错）并保存；
2、接着进入到用户A的用户基本资料页面，接着点击验证按钮，进入到验证页面，直接点击发送按钮
结果：页面提示发送短信失败，请重新输入
备注：直接在用户基本资料-修改资料页面修改手机号并保存，再进入到验证页面点击验证按钮，页面提示发送短信成功
期望：不管在哪个页面对用户资料进行修改并成功保存后，在验证页面均可以发送短信成功

**Comment by TeemolSparrow** [comment]
显示失败是为了防止用户在一段时间内发送过多的验证请求

**Comment by wjgao** [comment]
v0.5版本上，此问题已处理，复测通过，关闭
