### ISSUE TITLE
V0.4 车辆管理中的“排量”只能允许输入正数

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#390]
路径：车辆管理-新增/修改页面
操作：排量输入为非正数，比如010.01，汉字、负数后点击保存按钮
结果：保存成功，在车辆管理列表中，排量显示为非正数，不合理
期望：排量只能输入正数

**Comment by dongliu1** [comment]
已完成

**Comment by wjgao** [comment]
v0.5版本上，此问题已处理，复测通过，关闭
