### ISSUE TITLE
用户注册页面

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#4]
# 用户注册页面

+ 仿github风格的用户注册(极简风格)
+ 注册第1步只出现必填的三个字段 : 用户名,密码,电话号码
+ 点注册钮后, 进入第2步,填写 昵称, 在用户填写之前,自动产生一个
+ 确定之后,调用 HTTP POST /user 提交信息  #2
+ 用户填写用户名时,检测是否已存在
+ 用户填写密码时,检测是否符合密码策略(最少长度)
+ 用户填写电话号码时,检测是否已注册,是否合法
+ 双语支持(简体中文+US English)
![signup](https://cloud.githubusercontent.com/assets/5030312/9077015/d3327296-3b5b-11e5-957b-b447fd96113c.png)

**Comment by jiangli0509** [comment]
已做完，代码已合并到dev，访问：http://localhost:8080/web/index 即可
存在的问题：1.无判断用户是否存在API 2.无判断手机号是否存在API 3.无注册API

**Comment by jiangli0509** [comment]
请尽快检查完成是否合格以及分配下一个issue
