### ISSUE TITLE
组织查询API无法通过组织简码查询

### ISSUE THREAD

**Issue by TeemolSparrow** [HP-Enterprise/BriAir#406]
新增组织前需要判断组织简码是否已存在，现在无法判断
[OrganizationController.java#L217-L265](https://github.com/HP-Enterprise/BriAir/blob/6db7fb96b27a7698febd1b52ad02fce9cb1d4df3/src/main/java/com/hp/briair/controller/OrganizationController.java#L217-L265)

**Comment by tiandashen** [comment]
c4cb0f30d3bc437e4d5730be94bbb2abf18bfcc9
37f14434e45b52a48a766c28c1cdbf69d7fae355
已完成

**Comment by tiandashen** [comment]
37f14434e45b52a48a766c28c1cdbf69d7fae355
已完成

**Comment by TeemolSparrow** [comment]
前端测试已通过
