### ISSUE TITLE
根据oid查询车辆API测试不通过

### ISSUE THREAD

**Issue by TeemolSparrow** [HP-Enterprise/BriAir#407]
https://github.com/HP-Enterprise/BriAir/blob/6db7fb96b27a7698febd1b52ad02fce9cb1d4df3/src/main/java/com/hp/briair/controller/VehicleController.java#L161-L231

**Comment by AceBear** [comment]
写2个单元测试:传入oid,获取此oid对应组织中的所有车辆
+ 一个成功获取了车辆信息的测试
+ 一个由于权限不足的测试
