### ISSUE TITLE
数据库SQL脚本自动化执行

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#41]
+ 使用命令行工具自动化执行数据库脚本
+ 使用spring-boot + flyway [howto-execute-flyway-database-migrations-on-startup](http://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html#howto-execute-flyway-database-migrations-on-startup)

请参见 #16 框架计划

**Comment by jack-luj** [comment]
Mysql source命令可以吗
