### ISSUE TITLE
删除组织API测试不通过

### ISSUE THREAD

**Issue by TeemolSparrow** [HP-Enterprise/BriAir#410]
https://github.com/HP-Enterprise/BriAir/blob/6db7fb96b27a7698febd1b52ad02fce9cb1d4df3/src/main/java/com/hp/briair/controller/OrganizationController.java#L177-L189

删除组织后台报错：
SQL Error: 1451, SQLState: 23000
Cannot delete or update a parent row: a foreign key constraint fails (`sms`.`t_authoritygroup`, CONSTRAINT `t_authoritygroup_ibfk_1` FOREIGN KEY (`oid`) REFERENCES `t_organization` (`Id`))

**Comment by AceBear** [comment]
参见 #414
