### ISSUE TITLE
JAVA: 单元测试 HTTP GET /api/org/{oid}/group/{agid}/authority

### ISSUE THREAD

**Issue by TeemolSparrow** [HP-Enterprise/BriAir#413]
https://github.com/HP-Enterprise/BriAir/blob/cd5f11c8cd6426b2224629480011fb77befb55aa/src/main/java/com/hp/briair/controller/AuthorityController.java#L419-L448

后台报错：org.hibernate.InstantiationException: No default constructor for entity:  : com.hp.briair.entity.AuthoritygroupRelatived

**Comment by AceBear** [comment]
增加一个单元测试,来暴露这个问题
