### ISSUE TITLE
删除权限组API测试不通过

### ISSUE THREAD

**Issue by TeemolSparrow** [HP-Enterprise/BriAir#416]
https://github.com/HP-Enterprise/BriAir/blob/cd5f11c8cd6426b2224629480011fb77befb55aa/src/main/java/com/hp/briair/controller/AuthorityController.java#L262-L287

后台报错：org.hibernate.InstantiationException: No default constructor for entity:  : com.hp.briair.entity.AuthoritygroupRelatived

**Comment by Liujingguo91year** [comment]
已完成 41e5624

**Comment by TeemolSparrow** [comment]
测试已通过
