### ISSUE TITLE
V0.5 车辆管理 新增保存后发动机类型显示不正确

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#438]
路径：车辆管理 添加页面
操作：在添加窗口中输入VIN和TBOX，发动机类型为默认值（即涡轮增压），点击保存按钮，如下图所示
![a1](https://cloud.githubusercontent.com/assets/13793913/10154552/56b038dc-669b-11e5-8239-145b4078c037.jpg)
结果：在车辆管理列表中该新增车辆的发动机类型显示为 自然吸气，如下图所示
![a2](https://cloud.githubusercontent.com/assets/13793913/10154565/7cf158dc-669b-11e5-8faa-854841ca26e1.jpg)
期望：新增车辆时发动机类型为默认值保存成功后，在列表中该车辆数据的发动机类型应该显示为新增时的默认值

**Comment by Septemberwh** [comment]
当没有填入排量保存时，选择发动机的类型并没有什么用，都默认为涡轮增压；如果填入了排量并且选了发动机类型保存成功，点击修改，所呈现的数据都是正确的。页面上没有要求需要呈现发动机的类型，故删除这一个显示的字段。

**Comment by wjgao** [comment]
在V0.8版本上此问题已处理，复测通过，关闭
