### ISSUE TITLE
V0.5 车辆管理 只能新增一条车辆数据，再新增时TOMCAT报错

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#439]
路径：车辆管理模块
前提：车辆管理列表中存在一条车辆数据
操作：在车辆管理列表页面中点击添加按钮，在弹出的窗口中输入新的VIN和TBOX值后点击保存按钮
结果：当前窗口无任何反应，TOMCAT报错，如下图所示
![qq 20150929112313](https://cloud.githubusercontent.com/assets/13793913/10154631/83b4e0d4-669c-11e5-8cd3-8dc57e8d00aa.jpg)
期望：车辆添加功能正常

**Comment by AceBear** [comment]
+ 写一个测试用例,暴露此问题
+ 解决此问题

**Comment by wangh2015** [comment]
3fa668ce189712354ffb737aae0c9be90dfafdfb #439 已完成！

**Comment by wjgao** [comment]
在V0.7版本上此问题已处理复测通过，关闭
