### ISSUE TITLE
V0.5 车辆管理 发动机类型显示有问题，见描述

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#441]
路径：车辆管理模块
操作：
1、新增车辆时发动机类型选择为 自然吸气（如下图所示） 然后保存成功
![a1](https://cloud.githubusercontent.com/assets/13793913/10154748/e495e46a-669d-11e5-952c-fc906db994fd.jpg)
2、接着进入到该车辆的修改信息窗口
结果：发动机类型变为 涡轮增压，如下图所示
![a2](https://cloud.githubusercontent.com/assets/13793913/10154763/07733f64-669e-11e5-83ef-60ea6b7c3a5a.jpg)
期望：发动机类型显示正常
备注：修改时改为 涡轮增压（不是默认选择，是先选择自然吸气，然后再选择涡轮增压）保存后，列表中还是显示为 自然吸气

**Comment by Septemberwh** [comment]
同 #438，不填排量，发动机类型都默认为涡轮增压

**Comment by wjgao** [comment]
在V0.7版本上此问题已处理，复测通过，关闭
