### ISSUE TITLE
V0.5 登录首页 未输入用户名和密码的情况下不要显示出任何提示信息

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#444]
路径：用户登录页面
操作：
1、在平台用户注册页面点击登录按钮
2、忘记密码页面点击返回按钮
结果：在用户登录页面，未输入用户名和密码的情况下，页面显示出 用户名或密码错误，请重新输入 的提示信息，不合理
期望：在未输入用户名和密码的情况下，登录页面不要出现任何提示信息
备注：成功修改了密码后跳转到的登录页面也存在此问题

**Comment by wjgao** [comment]
在V0.7版本上，登录窗口未输入账号和密码的情况下，依然显示出 “用户名或密码错误，请重新输入”提示信息

**Comment by Septemberwh** [comment]
没有输入任何信息就点击登录，就相当于是登录错误，应该是有‘提示信息’的。

**Comment by wjgao** [comment]
同意此解释，关闭
