### ISSUE TITLE
V0.5 组织管理 组织名称和组织编码重复输入 页面无任何提示

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#446]
路径：组织管理模块-新增/修改窗口
操作：组织名称和组织编码输入重复，点击保存按钮
结果：当前窗口中无任何提示信息出现，且系统无任何反应
期望：组织名称和组织编码输入重复的情况下，点击保存按钮，分别在组织名称和或组织编码输入框下方显示出 组织名称已存在，请重新输入 的提示内容和 组织编码已存在，请重新输入 的提示内容

**Comment by wjgao** [comment]
在V0.8版本中组织信息修改页面无数据显示，所以修改页面的验证无法测试，新增时已有验证。待其他问题解决后再进行此问题的复测

**Comment by wangh2015** [comment]
已修复，测试通过

**Comment by wjgao** [comment]
在V0.9版本中此问题已处理，复测通过，关闭
