### ISSUE TITLE
V0.5 组织管理 修改页面 组织名称和组织描述未做输入限制

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#448]
路径：组织管理-修改页面
操作及结果：
1、组织名称输入长度超过50个字符后点击保存按钮，保存成功；
2、组织描述输入超过100个字符后点击保存按钮，系统无反应，TOMCAT报错
期望：
1、修改页面中的组织名称输入长度最大不能超过50个字符
2、修改页面中的组织描述输入长度最大不能超过100个字符，在此范围内保存成功

**Comment by TeemolSparrow** [comment]
此问题已修复，V0.5版本中暂时没有

**Comment by wjgao** [comment]
在V0.8版本上修改页面无数据显示无法复测，但新问题处理后再进行此问题的复测

**Comment by jiangli0509** [comment]
查询/修改组织的权限引起的

**Comment by jiangli0509** [comment]
#635

**Comment by jiangli0509** [comment]
已验证通过

**Comment by wjgao** [comment]
在V0.9版本中此问题依然存在，是组织修改页面，修改页面！！！！！！！

**Comment by AceBear** [comment]
@jiangli0509 因有其它事情,这个ISSUE转给 @jefferyxq 处理

**Comment by wjgao** [comment]
在V0.10版本中，在组织修改页面，组织名称长度超过50个字符点击保存按钮，系统无任何反应。
期望：组织名称长度不能超过50个字符的，当长度超过50个字符点击保存按钮时，当前窗口的组织名称输入框下方出现提示 组织名称不能超过50字符 的信息（与添加组织窗口的提示保持一致）

**Comment by liuyakun** [comment]
2be91d68e07844264a13cc00791a2fb0b5096966   已完成组织名称长度、组织描述长度验证
