### ISSUE TITLE
V0.5 组织管理 删除功能未实现

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#450]
路径：组织管理模块-组织信息页面
操作：点击“组织详情”区域中的删除按钮，再在弹出的窗口中点击确认按钮
结果：页面跳转回组织管理列表页面，该组织数据未删除，依然现在是列表中

**Comment by TeemolSparrow** [comment]
API报错 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`sms`.`t_authoritygroup`, CONSTRAINT `t_authoritygroup_ibfk_1` FOREIGN KEY (`oid`) REFERENCES `t_organization` (`Id`))

**Comment by wjgao** [comment]
在V0.8版本上此问题已处理，复测通过，关闭
