### ISSUE TITLE
V0.5 组织管理 添加用户窗口中的用户数据显示不全

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#451]
路径：组织管理-组织信息-用户信息-添加用户窗口
前提：用户数已经超过10条，如下图所示
![a1](https://cloud.githubusercontent.com/assets/13793913/10157539/7953eb78-66bd-11e5-9e2d-b1dc71c5495c.jpg)
操作：进入到添加用户窗口中 或者输入查询条件点击查询按钮
结果：当前窗口中只显示出10条用户数据，如下图所示
![a2](https://cloud.githubusercontent.com/assets/13793913/10157699/e2de05dc-66be-11e5-89c4-e335286d277e.jpg)
期望：多余10条的通过翻页方式显示出来

**Comment by TeemolSparrow** [comment]
已使用分页方法解决此问题

**Comment by TeemolSparrow** [comment]
已使用分页解决此问题，Admin无法添加用户是由于Admin实质上并不具备所有权限造成的（Admin起初通过SQL默认加入，并未赋权）

**Comment by wjgao** [comment]
在V0.9版本中此问题处理，复测通过，关闭
