### ISSUE TITLE
V0.5 组织管理-组织信息 用户信息区域 用户数据显示不全

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#455]
路径：组织管理-组织信息 用户信息区域 
操作：成功添加了11条数据（如下图所示）
![a1](https://cloud.githubusercontent.com/assets/13793913/10157940/fcac7b40-66c0-11e5-9be7-38fa42ee116f.jpg)
结果：在组织信息-用户信息区域只显示出10条用户数据，如下图所示
![a2](https://cloud.githubusercontent.com/assets/13793913/10158082/1d3919d0-66c2-11e5-8138-dd3cab7603bb.jpg)
期望：组织管理-用户信息区域 添加成功的用户数能全部显示出来

**Comment by TeemolSparrow** [comment]
已修改为分页显示

**Comment by wjgao** [comment]
在V0.9版本中此问题已处理，复测通过，关闭
