### ISSUE TITLE
V0.5 组织管理-组织信息 用户信息修改后自动被删除了

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#456]
路径：组织管理-组织信息 用户信息区域
前提：用户信息区域已存在用户数据，如下图所示，以图中蓝框数据为例
![a1](https://cloud.githubusercontent.com/assets/13793913/10158165/b4506760-66c2-11e5-94e5-1b89b1d83076.jpg)
操作：在用户管理模块页面修改用户昵称或手机号并保存成功（如下图所示），接着回到组织管理-用户信息显示区域
![a2](https://cloud.githubusercontent.com/assets/13793913/10158212/12df6c40-66c3-11e5-842c-60a22728bbaa.jpg)
结果：上图中蓝框的用户被系统自动删除了，不显示在用户信息区域了，如下图所示
![a3](https://cloud.githubusercontent.com/assets/13793913/10158220/194566b6-66c3-11e5-9be7-b0344fec14cd.jpg)
期望：在其他页面修改用户信息不会影响组织管理-用户信息的数据
备注：用户基本信息和用户基本信息-验证页面进行了修改和验证操作后，该用户也被系统自动删除于组织了

**Comment by rodbate** [comment]
没bug

**Comment by AceBear** [comment]
和 @wjgao  沟通,看看是哪种情况
1. @wjgao 误报了(概率不大), 如果是这种情况,直接让 @wjgao 关掉这个ISSUE
2. @wjgao 测试的那个版本上有这个BUG,但你工作的当前版本上没有(很有可能), 如果是这种情况,需要给出分析,为什么当前版本没有这个BUG了(可能的原因: 已经被修复了 或 由于功能变化,BUG的前提条件不存在 或 其它原因)

**Comment by wjgao** [comment]
在下一个版本中进行验证

**Comment by wjgao** [comment]
在V0.8版本中此问题无法测试，因为在组织管理里面无法添加用户，待解除添加用户问题后再测试此问题

**Comment by jiangli0509** [comment]
@wjgao  http://121.40.157.200/ 现在的测试网站已无此bug出现。添加用户也已修复，可复测。

**Comment by wjgao** [comment]
在V0.9版本上，无法修改用户信息，所以此问题暂时无法复测，等待修改用户信息的BUG处理后再进行测试

**Comment by wangh2015** [comment]
经测试，因为权限控制，只允许用户本人修改自己的详细信息。

**Comment by AceBear** [comment]
组织中的管理员应当可以修改组织成员除(ID,用户名)以外的其它信息

**Comment by wangh2015** [comment]
已经修改完成

**Comment by wjgao** [comment]
在V0.10版本中此问题已处理，复测通过，关闭
