### ISSUE TITLE
V0.5 建议 组织后不要自动创建权限组

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#458]
路径：组织管理
操作：新增组织
结果：新增的组织自动创建了具有admin和user的权限
建议：新增组织后最好不要自动创建权限组，这样比较安全

**Comment by AceBear** [comment]
虽然创建了权限组,但组中并没有用户,此举是为了方便用户操作

**Comment by wjgao** [comment]
解释合理，在V0.8版本上关闭此问题
