### ISSUE TITLE
创建权限组API需要修改

### ISSUE THREAD

**Issue by TeemolSparrow** [HP-Enterprise/BriAir#477]
[AuthorityController.java#L144-L173](https://github.com/HP-Enterprise/BriAir/blob/1c48e5bdfb3874c69684ccdf9030f1382ee10654/src/main/java/com/hp/briair/controller/AuthorityController.java#L144-L173)

[AuthorityGroup.java](https://github.com/HP-Enterprise/BriAir/blob/cd5f11c8cd6426b2224629480011fb77befb55aa/src/main/java/com/hp/briair/entity/AuthorityGroup.java)

AuthorityGroup 类中  authRelativedsSet 属性为set类型，前端无法正确传递
接收参数类 AuthorityGroup 需改为对应的VO类型

**Comment by TeemolSparrow** [comment]
#453 被此任务 block

**Comment by Liujingguo91year** [comment]
已完成 5fa8767ce64bb05c041ac9aa389e22fbf8a014e4

**Comment by Liujingguo91year** [comment]
创建权限组做了修改   5bd09934445c927f8a2ee15d7e53ca81ed0af9bc

**Comment by Liujingguo91year** [comment]
进过讨论对功能做了修改   1075e78d785846c4700833decb51715680a032b9

**Comment by TeemolSparrow** [comment]
创建权限组过程并不需要传递权限参数，创建权限组权限过程由[AuthorityController.java#L448-L477](https://github.com/HP-Enterprise/BriAir/blob/60d9bc191d9eb0ec97bf35a2e6551cd76a8c117f/src/main/java/com/hp/briair/controller/AuthorityController.java#L448-L477)完成，固此API不作修改前端也能使用
