### ISSUE TITLE
BUG:创建权限组API未返回权限组ID，无法进行后续增加权限操作

### ISSUE THREAD

**Issue by TeemolSparrow** [HP-Enterprise/BriAir#509]
[AuthorityController.java#L149-L178](https://github.com/HP-Enterprise/BriAir/blob/60d9bc191d9eb0ec97bf35a2e6551cd76a8c117f/src/main/java/com/hp/briair/controller/AuthorityController.java#L149-L178)

为权限组增加权限需要agid
[AuthorityController.java#L448-L477](https://github.com/HP-Enterprise/BriAir/blob/60d9bc191d9eb0ec97bf35a2e6551cd76a8c117f/src/main/java/com/hp/briair/controller/AuthorityController.java#L448-L477)

**Comment by AceBear** [comment]
升级此API, 在返回的结果中,包含AGID

**Comment by jiangli0509** [comment]
已完成 720f376972223201b5d0f6af8a21aef978f3ceb6
