### ISSUE TITLE
HTTP: GET /api/login/{token}

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#52]
获取当前用户的登录信息

+ 以前这个API由 HTTP GET /api/login 提供
+ /api/login 现在改为"获取当前所有登录的用户"
+ 现在获取当前用户的登录信息由 GET /api/login/{token}承载

背景信息 #13 #17

**Comment by TeemolSparrow** [comment]
完成通过token获取当前用户信息修改及获取当前所有登录用户方法编写
