### ISSUE TITLE
完成保养记录的增加、删除和维护方法

### ISSUE THREAD

**Issue by TeemolSparrow** [HP-Enterprise/BriAir#529]
[CareRecordRepositoryDAO.java](https://github.com/HP-Enterprise/BriAir/blob/e4539d73b14c7d91aa9bf69d7ed28116ca209424/src/main/java/com/hp/briair/care/CareRecordRepositoryDAO.java#L6-L36)

```JAVA
addRecord(CareRecord record)
deleteRecord(int id)
updateRecord(CareRecord record)
```

**Comment by AceBear** [comment]
@TeemolSparrow 学习一下
https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

代码可以使用 代码区块,这样GITHUB会以颜色渲染代码块
