### ISSUE TITLE
JAVA：Org6S.addVehicle(Vehicle6S v)

### ISSUE THREAD

**Issue by jiangli0509** [HP-Enterprise/BriAir#535]
车辆绑定组织方法实现
* Org6S里面没有绑定这辆车直接绑定
* Org6S里面已绑定这辆车则不再绑定，返回该车已绑定
* 在Triclops里面写测试用例
* javaDoc
* 参见#504

**Comment by wangh2015** [comment]
7032b5f664b17445610d5f252d6ec44915e973fb  已完成并测试
