### ISSUE TITLE
JAVA：Org6S.deleteVehicle(Vehicle6S v)

### ISSUE THREAD

**Issue by jiangli0509** [HP-Enterprise/BriAir#536]
车辆解绑组织方法实现
* 组织已绑定这辆车则直接解绑
* 组织未绑定这辆车则返回未绑定信息
* 在Triclops里面写测试用例
* javaDoc
* 参见#504

**Comment by tiandashen** [comment]
https://github.com/HP-Enterprise/Triclops/commit/a3460d6551e95ec79171f26887cd42794139646c
已完成
