### ISSUE TITLE
v0.7 无法新增组织 点击保存按钮，系统无反应

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#551]
路径：组织管理
操作：输入组织名称和组织编码后点击保存按钮
结果：系统无任何反应 新增不成功

**Comment by tiandashen** [comment]
![qq](https://cloud.githubusercontent.com/assets/13448617/10476554/81d8f8b8-7281-11e5-8aa3-fb5ec25629de.jpg)
url应该是这样的，但js里面却是：
![qqq](https://cloud.githubusercontent.com/assets/13448617/10476619/0719ff36-7282-11e5-87d1-2bb530339120.jpg)

**Comment by dongliu1** [comment]
问题原因：经检查问题出在后台路径更改为“/api/org/{oid}”，加入了判断用户管理权限功能，而前台路径没更改，所以造成无法添加。
解决办法：更改前台路径，传入用户oid即可。
出现问题：通过获取token查询用户返回用户信息后，用户信息里并不包含用户oid这一项，因此无法传入oid，故而添加功能无法实现。
建议：使返回的用户信息里包含用户oid项。
PS：前台获取用户信息与oid传值已完成。

**Comment by tiandashen** [comment]
@AceBear “/api/org/{oid}”  前台用户是怎么得到这个oid的？
参见#108 后面由于需求修改加入oid

**Comment by AceBear** [comment]
+ 这个oid 不要放在URL路径里
+ 有一个可选的参数 oid 放在POST BODY中
+ 如果直接创建组织,不指定,那么代表,它是1号组织的直接子组织(不必在数据库中有条记录,因为我们约定,所有的组织都是1号组织的直接子组织,哪怕没有记录的也是)
+ 用户可以选择一个组织A,然后进入A详情,在"增加用户"增加车辆"的边上,再加上一个"增加子组织",那代表是创建A组织的子组织
+ 这个按钮不一定是"增加子组织", 也可能是更明确的"创建经销商", "创建车友群"这样的按钮

**Comment by tiandashen** [comment]
https://github.com/HP-Enterprise/BriAir/commit/a10b981d7e64c1936d867235e8ef42e7f4d909b3
已完成

**Comment by tiandashen** [comment]
2e85fcc4b904dd765db018fae62d314132fc7288
已修改完成

**Comment by wjgao** [comment]
在V0.8版本上此问题已处理，复测通过，关闭此BUG，由于在V0.8版本上只能使用超级管理员（admin）账号，所以在后面的版本中会使用一般账号进行测试，现在暂时关闭此BUG
