### ISSUE TITLE
测试用例：解除绑定车辆测试用例改进

### ISSUE THREAD

**Issue by jiangli0509** [HP-Enterprise/BriAir#555]
* 基于dev-unbindv#536开一个分支
* 在此分支优化OrganizationControllerTest.java里面解绑车辆测试的绑定车辆方法（解绑的方法是要基于添加一辆车以及绑定后再解绑），用新的Org6S.addVehicle(Vehicle6S v)来实现绑定

**Comment by wangh2015** [comment]
0b70d1e3dcb3409f35fbe172d8ccfb48575930d0  修改测试用例，check通过，并修改绑定车辆API，已PR

**Comment by jiangli0509** [comment]
测试有问题
