### ISSUE TITLE
系统更新UI

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#569]
+ 主菜单上增加一个系统更新的入口,直接点击进入,不要子菜单
+ 包管理页面 TAB页形式,每种终端类型一个
    包名称 创建日期 创建人(nick) 已更新/总数 禁用 删除
+ 终端类型管理页面
   终端类型的CRUD

**Comment by dongliu1** [comment]
已完成各项功能

**Comment by dongliu1** [comment]
#631
