### ISSUE TITLE
组织——规格化测试数据文档

### ISSUE THREAD

**Issue by jiangli0509** [HP-Enterprise/BriAir#571]
* 分支 dev-testdata#553 test/java/com.hp.briair/TestData.md
 - 相关文档
    - 组织
    - 权限组
    - 组织~权限组
* 文档格式例如：
  - 创建组织
     - 组织名称：测试组织
     - 组织类型：1
     - 组织描述：用于测试

**Comment by Liujingguo91year** [comment]
已修改   aa0e5b023af1848b6adaa9a882ce0322220c17f9

**Comment by jiangli0509** [comment]
已完成
