### ISSUE TITLE
V0.8 新注册的用户不能自主用于除查询功能以外的其他操作权限

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#573]
操作：新注册用户并登陆进系统
现象：在“我的爱车”、“车辆管理”、“组织管理”三个模块中分别用于“绑定车辆”、“添加车辆”和“添加组织”权限，实际上在新增车辆窗口中点击保存按钮，系统无反应。而在新增组织窗口中点击保存按钮时窗口自动关闭而新增的组织在超级管理员进入到系统后才显示出来。不合理
期望：新注册而未被分配权限的用户登录进系统后，在所有模块只能使用查询功能，新增、修改和删除功能按钮不应该显示出来

**Comment by AceBear** [comment]
我们需要同时达成以下2个目的
+ 供车主用户或管理员使用
+ 供我们自己测试API是否可用

特别的, 我们需要进行权限控制, 即 客户端可以调用他不具备权限的API,但服务器会禁止不合法的调用

解决办法: 设置$scope.debug = true变量
如果$scope.debug == false 那么表明是 正式运行环境,这时,所有不具备权限的菜单或按钮都不显示或灰化
如果$scope.debug == true,那么表明是 调试环境,这时,所有不具备权限的菜单或按钮仍然可以点击,但调用API后,服务器会返回错误
在顶部最右侧,增加一个切换钮,可以自由切换 $scope.debug的值

**Comment by AceBear** [comment]
暂时冻结
支撑这个功能,背后需要对权限部分有大量的升级
