### ISSUE TITLE
JAVA:终端类型5个API

### ISSUE THREAD

**Issue by Septemberwh** [HP-Enterprise/BriAir#576]
#### 支持以下5个API

协议 | 方法 | 路径 | 说明
------| -------| ------| -----------
HTTP |	GET  	| /update/term		                |   查询全部
HTTP |	POST 	| /update/term		                |   增加终端型号
HTTP |	GET	    | /update/term/{tid}		        |   查询单个终端型号
HTTP |	PUT	    | /update/term/{tid}		        |   修改终端型号
HTTP |	DELETE	| /update/term/{tid}		        |   删除终端型号

+ 每个API会有一个单独的controller方法
+ 另外设计一个类X,专门处理维护终端类型
+ API调用X中的方法完成功能
+ 必要的单元测试

详情请看#494

**Comment by liuyakun** [comment]
已完成并以push到分支
