### ISSUE TITLE
用户——规格化测试数据文档

### ISSUE THREAD

**Issue by jiangli0509** [HP-Enterprise/BriAir#580]
* 分支 dev-testdata#553 test/java/com.hp.briair/TestData.md
 - 相关文档
    - 用户
    - 组织~用户
    - 权限组~用户

**Comment by wangh2015** [comment]
831228800cdee5b1ec29f57b6340c076f1937896 新增用户测试数据 说明文档

**Comment by tiandashen** [comment]
@wangh2015 
等号前后要加上空格

**Comment by jiangli0509** [comment]
已完成
