### ISSUE TITLE
V0.8 组织管理-组织详情页面中无法添加用户、车辆

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#581]
路径：组织管理-组织详情页面-用户信息区域，车辆信息区域
前提：登录进系统的用户为超级用户，即 admin
操作：
1、在用户信息区域点击添加按钮然后选择一行用户数据后面的添加按钮；
2、在车辆信息区域点击添加按钮然后选择一行车辆数据后面的添加按钮
结果：
1、添加用户时点击添加按钮，系统提示 您未授权
2、添加车辆时点击添加按钮，系统无反应
期望：如果具有添加的权限，可以成功添加用户和车辆

**Comment by jiangli0509** [comment]
@AceBear 
* 添加用户在V0.8和dev版本测试均可成功
* 添加车辆系统无反应原因如下：
   1.在对应的controllerJS文件里面没有找到addVehicle(v.id)方法。（rodbate写的）

**Comment by wjgao** [comment]
在V0.9版本中此问题已处理，复测通过，关闭
