### ISSUE TITLE
V0.8 新增组织成功后，在组织修改页面无任何数据显示出来

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#584]
路径：组织管理-修改组织页面
前提：使用的账号为超级管理员，即admin
操作：成功新增一个组织数据（如下图所示），然后在进入到该组织的修改页面
![a1](https://cloud.githubusercontent.com/assets/13793913/10509025/1e9c7fc2-735d-11e5-8066-646a4cea6dab.jpg)
结果：返回到组织详情页面和进入到修改页面，无任何数据显示出来（如下两张图所示）
![a2](https://cloud.githubusercontent.com/assets/13793913/10509060/61ebdc32-735d-11e5-97ee-830602b44df9.jpg)

![a3](https://cloud.githubusercontent.com/assets/13793913/10509068/727b2d0a-735d-11e5-89d3-a27cb73c8b76.jpg)
期望：成功新增组织后，在组织详情和修改组织页面能正常显示出正确的组织数据

**Comment by jiangli0509** [comment]
#344 未按要求完成导致，已把详细原因回复在原任务 @wangh2015

**Comment by wangh2015** [comment]
65ab255e140b97d9d8c6c5319827d1d1c2d2a506

**Comment by wjgao** [comment]
在V0.9版本中此问题已处理，复测通过，关闭
