### ISSUE TITLE
V0.8 新增车辆成功后，在修改车辆信息窗口中无数据显示

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#587]
路径：车辆管理-修改车辆信息
前提：使用的账号为超级管理员，即admin 
操作：在车辆管理模块成功新建一条车辆数（如下图所示），接着进入到此车辆的‘修改车辆信息’窗口中
![a1](https://cloud.githubusercontent.com/assets/13793913/10509196/07c7d390-735e-11e5-8b0d-3991128098c5.jpg)
结果：“修改车辆信息”窗口中无车辆数据显示出来，如下图所示
![a2](https://cloud.githubusercontent.com/assets/13793913/10509208/22efbce6-735e-11e5-980a-ed8b58000c79.jpg)
期望：“修改车辆信息”窗口中车辆数据显示正常

**Comment by jiangli0509** [comment]
增加一号组织管理员可以修改车辆权限

**Comment by wangh2015** [comment]
测试可以，请Merge 最新代码

**Comment by wjgao** [comment]
在V0.9版本中此问题已处理，复测通过，关闭
