### ISSUE TITLE
组织——规格化测试数据添加

### ISSUE THREAD

**Issue by jiangli0509** [HP-Enterprise/BriAir#590]
* 基于dev-testdata#553新开分支
* 统一调用repository方法实现
* 有两次以上同样的代码写成共用方法
* 实现可多次执行，存在的数据不能重复添加

**Comment by Liujingguo91year** [comment]
已完成  #74caec5

**Comment by Liujingguo91year** [comment]
74caec53a460e08df9b01cca1bf5a828ec90e16d
已完成

**Comment by jiangli0509** [comment]
问题
1.注释错误，@param后面要有参数中文注释
2.优化返回值代码，默认返回null只返回一次就ok
3.添加权限组和给权限组赋予权限都没有做是否已存在判断

**Comment by Liujingguo91year** [comment]
收到，现在就改



jgliu@incardata.com.cn
 
发件人： 江黎
发送时间： 2015-10-19 11:15
收件人： HP-Enterprise/BriAir
抄送： 刘经国
主题： Re: [BriAir] 组织——规格化测试数据添加 (#590)
问题
1.注释错误，@param后面要有参数中文注释
2.优化返回值代码，默认返回null只返回一次就ok
3.添加权限组和给权限组赋予权限都没有做是否已存在判断
