### ISSUE TITLE
缺少通过tboxsn字段查询车辆API

### ISSUE THREAD

**Issue by TeemolSparrow** [HP-Enterprise/BriAir#599]
#374  号BUG需要验证TBOX唯一性

**Comment by AceBear** [comment]
修改一下API,增加对一个查询参数的支持

**Comment by tiandashen** [comment]
e7a8c3eb0401a94674b671178cc2cf2ff388b8c1
https://github.com/HP-Enterprise/Triclops/commit/cbafedce9c64869a7adc4d35f258b772ecdaa88e
已完成

**Comment by Liujingguo91year** [comment]
测试发现异常

java.lang.NullPointerException: null
	at com.hp.triclops.repository.VehicleRepositoryDAO.findVehiclesByKeys(VehicleRepositoryDAO.java:68)
	at com.hp.briair.controller.VehicleController.list(VehicleController.java:338)

**Comment by tiandashen** [comment]
378383a0e71604558e9b66f065b63886f859bcbb
https://github.com/HP-Enterprise/Triclops/commit/5fc9f5b75e57625b2c5c4e27e6ef83006634ecad
已完成

**Comment by jiangli0509** [comment]
存储过程里面没有tboxsn查询

**Comment by tiandashen** [comment]
d8f74d2249906925c7063236bcdb133cec3b5773
https://github.com/HP-Enterprise/Triclops/commit/b992f337f001ed95cf6d8543aacff4a529a71c62
已完成

**Comment by jiangli0509** [comment]
测试通过
