### ISSUE TITLE
JAVA:系统跟新  条件查询

### ISSUE THREAD

**Issue by Septemberwh** [HP-Enterprise/BriAir#616]
1.GET  "/api/update/term/{tid}/package"
2.GET  "/api/update/term"
添加所对应实体的参数查询（精确查询，模糊查询）
可以参考user,vehicle里的查询
对应分支 dev-#494-4

ref #494 系统更新设计

**Comment by liuyakun** [comment]
模糊查询，条件查询已完成

**Comment by Septemberwh** [comment]
[UploadController.java#L117_L121](https://github.com/HP-Enterprise/BriAir/blob/dev-%23494-4/src/main/java/com/hp/briair/controller/UploadController.java#L117_L121)
将此代码整理到对应的manager

**Comment by liuyakun** [comment]
已修改
