### ISSUE TITLE
JAVA:系统更新 补充更新包的修改API

### ISSUE THREAD

**Issue by Septemberwh** [HP-Enterprise/BriAir#625]
更新包心在会禁用和可用的状态，现在提供此API

**Comment by liuyakun** [comment]
升级包修改已完成

**Comment by AceBear** [comment]
@liuyakun 标记一下 commit or PR

**Comment by Septemberwh** [comment]
已将available修改为1（可用），2（禁用）的形式

**Comment by Septemberwh** [comment]
![image](https://cloud.githubusercontent.com/assets/9412495/10575723/06d8a0a0-7691-11e5-93f6-7b374ee2b6f8.png)
这里返回为null的时候，在controller中抛出一个对应的异常

**Comment by liuyakun** [comment]
改善了升级包修改的方法
