### ISSUE TITLE
BUG：管理员访问车辆信息权限问题

### ISSUE THREAD

**Issue by TeemolSparrow** [HP-Enterprise/BriAir#632]
现象：
①使用管理员账户登录
②在车辆管理界面增加一台车
③使用API：/api/vehicle 查询所有车，可以查询到这台车
④使用API：/api/vehicle/{vid} 查询刚插入的车辆，后台显示 “无权限”

推论：既然此用户能查询所有车辆，那就应该能查询单台车辆

影响： 管理员在车辆管理界面查询到车辆后，点击“保养”信息栏跳转到保养信息界面后，界面无法显示车辆信息，后台显示无权限 GET http://localhost:8080/api/vehicle/6 401 (Unauthorized)

**Comment by tiandashen** [comment]
1号组织管理员执行以上操作时没有问题的，只不过，其他组织管理员会添加不了车辆，原因：在页面上添加车辆的时候，没有传入oid，后台接收的vehicleShow里面的oid就为null，那么次oid就会默认为1，就会判断是否为1号组织管理员，然而并不是，就会出现无权限

**Comment by TeemolSparrow** [comment]
此问题已修复，测试通过
