### ISSUE TITLE
JAVA: unchecked 

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#633]
+ $\DataCenter\src\main\java\com\hp\data\core\AbstractConversion.java:146: 警告: [unchecked] 未经检查的转换
+ $\DataCenter\src\main\java\com\hp\data\util\ClassScanner.java:64: 警告: [unchecked] 参数化 vararg 类型Class<? extends Annotation>的堆可能已受污染
+ $\DataCenter\src\main\java\com\hp\data\util\ClassScanner.java:72: 警告: [unchecked] 参数化 vararg 类型Class<? extends Annotation>的堆可能已受污染
+ $\DataCenter\src\main\java\com\hp\data\util\PackageEntityManager.java:22: 警告: [unchecked] 对于类型为Class<? extends Annotation>[]的 varargs 参数, 泛型数组创建未经过检查
+ $\BriAir\src\main\java\com\hp\briair\utils\ResolveBase.java:3: 警告: BASE64Decoder是内部专用 API, 可能会在未来发行版中删除
+ $\BriAir\src\main\java\com\hp\briair\utils\ResolveBase.java:17: 警告: BASE64Decoder是内部专用 API, 可能会在未来发行版中删除
+ $\BriAir\src\test\java\com\hp\briair\MessageControllerTest.java:24: 错误: 编码UTF-8的不可映射字符
+ $\BriAir\src\test\java\com\hp\briair\ResolveBaseTest.java:15: 错误: 编码UTF-8的不可映射字符

**Comment by jack-luj** [comment]
@liuyakun  处理BriAir里面你的几个文件，UTF-8警告的 Ctrl+A-改下UTF-8编码然后Ctrl+V就应该可以了  ，BASE64的可能需要换个转换类,可以考虑Apache Commons Codec
http://commons.apache.org/proper/commons-codec/download_codec.cgi
