### ISSUE TITLE
OrganizationController权限控制修改

### ISSUE THREAD

**Issue by jiangli0509** [HP-Enterprise/BriAir#644]
* 支持1号组织管理员有所有权限
* 权限判断从默认Admin权限改成根据传入参数判断
* 基本dev-authorityenhance切分支，调用方法已提供

**Comment by wangh2015** [comment]
10b68f110ac855251a4adcebe5ef15a5cf2ace2c 已测试，同时有两个问题：创建组织，关联组织ID 是固定的；查询组织列表代码需要优化

**Comment by tiandashen** [comment]
OrganizationController的168行，格式没有改过来

**Comment by wangh2015** [comment]
1a82e17bf35c514935b74d77b5911a7742ef3495 已修改
