### ISSUE TITLE
UserController权限控制修改

### ISSUE THREAD

**Issue by jiangli0509** [HP-Enterprise/BriAir#645]
* 支持1号组织管理员有所有权限
* 权限判断从默认Admin权限改成根据传入参数判断
* 基本dev-authorityenhance切分支，调用方法已提供

**Comment by wangh2015** [comment]
b37f4ae3bd54a9465e0b1cb1a63112900e8e45a2 已测试

**Comment by tiandashen** [comment]
api/user查询用户里面的权限控制的格式未修改

**Comment by jiangli0509** [comment]
什么格式？

**Comment by tiandashen** [comment]
权限判断没有从默认Admin权限改成根据传入参数判断

**Comment by wangh2015** [comment]
680985dd2d5a76081a3a9ee10d0ca4244a930e30 已经修改 测试
