### ISSUE TITLE
VehicleController权限控制修改

### ISSUE THREAD

**Issue by jiangli0509** [HP-Enterprise/BriAir#646]
* 支持1号组织管理员有所有权限
* 权限判断从默认Admin权限改成根据传入参数判断
* 基本dev-authorityenhance切分支，调用方法已提供

**Comment by tiandashen** [comment]
0caa3cd0fca86b3a8d73bdf6955a0c775cce0580
已完成

**Comment by wangh2015** [comment]
检查的问题：删除VehicleController 没有使用的包， /api/vehicle里面无需判断token不等于null

**Comment by tiandashen** [comment]
261534859df470368d516e4a1ca22e01b0eeefb4
已修改完成
