### ISSUE TITLE
报警信息数据-中文翻译

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#664]
## 报警信息数据-中文翻译
 - 将 **t_warning_message_conversion** 表里**message_en**字段翻译结果写入到**message_zh**
    - 修改插入语句  *insert into t_warning_message_conversion(message_id,message_en) values(1,'Airbag or Restraint sytem malfunction');* 为 insert into t_warning_message_conversion(message_id,message_en,message_zh) values(1,'Airbag or Restraint sytem malfunction','安全气囊或者座椅安全带系统失灵','');
    - 建表语句 
```sql
    CREATE TABLE t_warning_message_conversion (
        id int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
        message_id smallint(3) NOT NULL COMMENT '报警消息id',
        message_en varchar(100) NOT NULL COMMENT '英文消息',
        message_zh varchar(100) NOT NULL COMMENT '中文消息',
        PRIMARY KEY (id)
     ) DEFAULT CHARSET=utf8 COMMENT='报警消息表';
```
 - 完成后执行**sql**进行验证

**Comment by shuzihao** [comment]
已经完成
