### ISSUE TITLE
BUG：通过组织名称、组织简码查询组织返回结果不正确，导致新增组织过程出错

### ISSUE THREAD

**Issue by TeemolSparrow** [HP-Enterprise/BriAir#667]
背景：新增组织需要进行组织名称及简码唯一性验证   #446

步骤：①使用管理员登录； ②使用浏览器测试API:  api/org?orgName=123
期望：返回组织名称为“123”的组织
实际：返回500错误

![qq 20151021094851](https://cloud.githubusercontent.com/assets/13936823/10625716/f8621a26-77d8-11e5-8e7b-9eb0a2f8a9c8.png)

步骤：①使用管理员登录； ②使用浏览器测试API:  api/org?breCode=123
期望：返名组织简码为“123”的组织
实际：返回了组织简码不为“123”的组织

![qq 20151021095117](https://cloud.githubusercontent.com/assets/13936823/10625740/5a665d4a-77d9-11e5-84a3-82ac5530bcb7.png)

**Comment by wangh2015** [comment]
#678分支代码测试通过

**Comment by TeemolSparrow** [comment]
fuzzy条件无效

**Comment by tiandashen** [comment]
0042a765b7fe71f430d514f05261f80524202fec
https://github.com/HP-Enterprise/Triclops/commit/3cd6b9b352764841263d0508f8336f19b97fe348
已完成

**Comment by TeemolSparrow** [comment]
#777  

查询结果依然有问题：

![qq 20151027134526](https://cloud.githubusercontent.com/assets/13936823/10750514/3c9deb52-7cb1-11e5-9610-908193356411.png)

**Comment by AceBear** [comment]
要求补一个针对此问题的单元测试

**Comment by tiandashen** [comment]
0c51d39105c9bae872e251b2b789cf6da292b84d
已完成，并写好测试类

**Comment by TeemolSparrow** [comment]
查询结果还是不对

**Comment by tiandashen** [comment]
4bdd7740e97ba486efbf0592ee2d14ace33
已完成
