### ISSUE TITLE
JAVA : 语言增强

### ISSUE THREAD

**Issue by Septemberwh** [HP-Enterprise/BriAir#670]
完成API:GET /api/login/language

1.解析HTTP请求中的Accept-Language，并对其进行排序；
2.将排序后的Accept-Language,绑定到HTTP响应中去，供前台使用(ref:Page,Page-Count);

ref：#651

**Comment by liuyakun** [comment]
代码已经提交

**Comment by Septemberwh** [comment]
添加此方法的测试类

**Comment by liuyakun** [comment]
测试方法已经提交

**Comment by liuyakun** [comment]
efcfaedecd38d5970197b07177f49bf28bc76da3 已完成

**Comment by Septemberwh** [comment]
测试方法，你只对HTTP请求验证了，并没有验证HTTP的的响应绑定了Accept-Language

**Comment by liuyakun** [comment]
ce24f1e5d943775c02f12eaacd2547cd93088a7a   已修改
