### ISSUE TITLE
JS:语言增强

### ISSUE THREAD

**Issue by Septemberwh** [HP-Enterprise/BriAir#673]
调用 API: GET /api/login/language

1.根据HTTP所返回的信息，获取到 Accept-Language的信息(ref：Page-Count的获取)
2.根据Accept-Language决定浏览器所要呈现的语言

ref:#651

**Comment by liuyakun** [comment]
8331189a292d67388c18cd4164d4bac657bc1434    已完成

**Comment by liuyakun** [comment]
31b4f0e2c17522d261c9e2aceb138dfe27c69612  修改
