### ISSUE TITLE
HTML:强化分页

### ISSUE THREAD

**Issue by Septemberwh** [HP-Enterprise/BriAir#679]
参考组织管理中详情页面的分页（将分页写成了一个指令的形式）。

将我们之前所写的分页，全部改为引用这个指令的方式。

**Comment by dongliu1** [comment]
已完成  dev-#679-ld

**Comment by dongliu1** [comment]
已完成路径跳转 037f13cb

**Comment by dongliu1** [comment]
已从dev上merge  2205bee5
