### ISSUE TITLE
整合升级版权限控制

### ISSUE THREAD

**Issue by jiangli0509** [HP-Enterprise/BriAir#682]
* 把#642 #644 #645 #646 的代码整合到一个新分支上
* 去掉原来的权限验证方法，保证能正常运行
* 期间针对权限控制优化的分支也一并merge过来

**Comment by wangh2015** [comment]
904a9adfafc0ac1da6c2698d65fdfd865d29f7f6 已经合并

**Comment by jiangli0509** [comment]
BUG:没有去掉原来的权限验证方法

**Comment by wangh2015** [comment]
986220e86cb8fa3edf3bb02850d0d21c26d19f03 已去掉原来的权限验证方法

**Comment by wangh2015** [comment]
2720318f4108274853aafeab3c475fe8420e3b4a  合并 #678
