### ISSUE TITLE
规格化测试数据——创建权限组

### ISSUE THREAD

**Issue by jiangli0509** [HP-Enterprise/BriAir#684]
问题：createAuthorityGroup方法会重复创建权限组
原因：authorityGroupRepository.findByIdAndOid(id, oid) 调用此方法是没有用的，因为还没有创建权限组就调用按id去查找是错误的。
正确做法：按照name和oid来查询

* 另外，把你写的测试方法都检查一遍

**Comment by Liujingguo91year** [comment]
已添加新的方法来查找权限组。findByOidAndName  
a06e910b

**Comment by jiangli0509** [comment]
已检查完成
