### ISSUE TITLE
JAVA: 修订API HTTP GET /api/org/{oid}/group/{agid}

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#686]
[AuthorityController.java#L184-L211](https://github.com/HP-Enterprise/BriAir/blob/bde1715d40b4554489cc7ff538e6beca8a37ff34/src/main/java/com/hp/briair/controller/AuthorityController.java#L184-L211)

增强这个API,返回权限组中包含的 "用户" 和 ~~"权限"~~

权限暂时可以不要,因为有另一个API做这个事

**Comment by TeemolSparrow** [comment]
将获取权限信息的代码加回来（删除线表示此功能已存在，并不是删除掉）
