### ISSUE TITLE
非一号组织管理员修改用户手机号码后台报错

### ISSUE THREAD

**Issue by wangh2015** [HP-Enterprise/BriAir#687]
路径：用户管理-修改用户信息
前提：使用的账号为 非一号组织管理员
操作：在用户管理列表，点击修改用户信息，填写用户表中不存在的手机号码，点击保存

![image](https://cloud.githubusercontent.com/assets/14209751/10630104/04520264-7807-11e5-97b8-fabbce545077.png)

结果： 修改用户手机号码没有保存成功，后台报空指针异常

![image](https://cloud.githubusercontent.com/assets/14209751/10630249/0788e37a-7808-11e5-83b5-abd21a92bed3.png)

期望：“修改用户信息”功能中 修改手机号码正常

**Comment by jiangli0509** [comment]
6b549516be6bc85e11906feca7f3a9789e3ef9a0

**Comment by tiandashen** [comment]
76cb117b1a3643f98dc9f748ec0b70ec396b31ed
已完成

**Comment by wangh2015** [comment]
已测试通过
