### ISSUE TITLE
组织查询API权限控制,非一号组织管理员能查到所有组织

### ISSUE THREAD

**Issue by wangh2015** [HP-Enterprise/BriAir#689]
路径：组织管理
前提：使用的账号为 非一号组织管理员
操作：在组织名称中输入一号组织管理员名称
![image](https://cloud.githubusercontent.com/assets/14209751/10631086/1804f3c8-780e-11e5-8fcd-af9415d1fded.png)

结果： 查询到一号组织的信息（权限控制失败）
期望：通过权限控制，只能查看到有权限的组织

**Comment by tiandashen** [comment]
fdbaa7ba18495c774f4522d4a7ede1455e8e016f
已完成

**Comment by wangh2015** [comment]
已测试
