### ISSUE TITLE
BUG:注册用户过程中，用户名唯一性检查问题

### ISSUE THREAD

**Issue by TeemolSparrow** [HP-Enterprise/BriAir#694]
前提：系统中已经存在用户名为admin的用户
步骤：①注册页面用户名栏输入admin ②点击密码输入框
现象：并没有提示admin用户已存在

![qq 20151021172551](https://cloud.githubusercontent.com/assets/13936823/10632863/82854936-7819-11e5-9dce-780ac2a4d6ff.png)

**Comment by jiangli0509** [comment]
9e4e848a 已完成

**Comment by wjgao** [comment]
在V0.10版本中此问题已处理，复测通过，关闭
