### ISSUE TITLE
TBOX的CRUD

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#702]
+ 设计一个对象(如 TBoxMgr,也可以换一个你喜欢的名字),来管理Tbox的增加,删除,查询
+ 设计一套API,由Controller对象承载,向客户端提供TBOX的管理能力,内部调用TBoxMgr完成功能

+ 在BriAir中,从Vehicle6S对象派生一个新的对象,由这个对象提供车辆和TBOX的绑定/解除能力
+ 修改车辆相关的API Controller,向客户端提供TBOX绑定/解除能力,内部实现调用上一步的派生类完成功能

**Comment by jiangli0509** [comment]
7aeae4c2c02a060eb0a428c81e512bdc22ad0353 已完成
