### ISSUE TITLE
javadoc all-in-one

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#712]
https://travis-ci.org/HP-Enterprise/BriAir

**Comment by AceBear** [comment]
PhoneBookManagement.java:26: warning: no description for @param
     * @param phoneBookShow

**Comment by AceBear** [comment]
TBoxMgr.java:45: warning: no @return
    public TBox addTBox(TBox tbox)

**Comment by AceBear** [comment]
:javadoc/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/uploadPackage/messageManager/MessageManager.java:104: warning: no @param for targetIds
    public int createMessage(Message message,MultipartFile file,String targetIds) throws Exception{
               ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/uploadPackage/messageManager/MessageManager.java:127: warning: no @param for targetIds
    public Message saveMessage(Message message,String targetIds){
                   ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/uploadPackage/messageManager/MessageManager.java:189: warning: no @param for uid
    public void messageCommunications(int uid,Message message,String targetIds){
                ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/uploadPackage/messageManager/MessageManager.java:189: warning: no @param for targetIds
    public void messageCommunications(int uid,Message message,String targetIds){
                ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/uploadPackage/messageManager/MessageManager.java:228: warning: no @param for targetType
    public void messageCommunications(int targetType ,int targetId,Message message,String targetIds){
                ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/uploadPackage/messageManager/MessageManager.java:228: warning: no @param for targetId
    public void messageCommunications(int targetType ,int targetId,Message message,String targetIds){
                ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/uploadPackage/messageManager/MessageManager.java:228: warning: no @param for targetIds
    public void messageCommunications(int targetType ,int targetId,Message message,String targetIds){

**Comment by AceBear** [comment]
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/repository/RosterRepositoryDao.java:49: warning: no @return
    public List<Roster> get(Integer id,Integer uid,Integer fid,Integer flag){

**Comment by AceBear** [comment]
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/AuditLogAop.java:53: warning: no @param for retVal
    public void AfterMethodReturn(JoinPoint joinPoint, Object retVal){
                ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/AuditLogAop.java:88: warning: no @param for e
    public void AfterMethodThrow(JoinPoint joinPoint, Exception  e) {
                ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/AuditLogController.java:46: warning: no description for @throws
     * @throws HttpException
       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/AuditLogController.java:49: warning: no @param for response
    public List<AuditLog> list(@RequestParam(value = "id",required = false)  Integer id,

**Comment by AceBear** [comment]
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/ExemptionController.java:22: warning: no description for @throws
     * @throws HttpException
       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/ExemptionController.java:35: warning: no description for @throws
     * @throws HttpException

**Comment by AceBear** [comment]
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/imageController.java:45: warning: no description for @throws
     * @throws HttpException
       ^

**Comment by AceBear** [comment]
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/PageController.java:31: warning: no description for @return
     * @return

**Comment by AceBear** [comment]
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/UploadController.java:141: warning: no @param for uploadName
    public List<PackageShow> getPackageList(@PathVariable("tid") int tid,

**Comment by AceBear** [comment]
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/UserController.java:167: warning: no @param for request
    public UserShow GetUser(@PathVariable("uid") int uid,HttpServletRequest request)throws HttpException{
                    ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/UserController.java:167: warning: no @throws for com.hp.briair.utils.HttpException
    public UserShow GetUser(@PathVariable("uid") int uid,HttpServletRequest request)throws HttpException{
                    ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/UserController.java:190: warning: no @param for token_resetPassword
    public UserShow ModifyUser(@PathVariable("uid") int uid, @RequestBody UserPwdAndMore userPwdAndMore,@CookieValue(value="token",required = false) String token,@CookieValue(value="token_resetPassword",required = false) String token_resetPassword,HttpServletRequest request)throws HttpException{
                    ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/UserController.java:289: warning: no description for @return
     * @return
       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/UserController.java:290: warning: no description for @throws
     * @throws Exception
       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/UserController.java:315: warning: no description for @return
     * @return
       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/UserController.java:316: warning: no description for @throws
     * @throws Exception
       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/UserController.java:319: warning: no @param for response
    public JsonResult modifyUserIcon(@PathVariable("uid") int uid, @RequestParam(value="file",required = false) MultipartFile file, HttpServletRequest request,HttpServletResponse response)throws Exception{

**Comment by AceBear** [comment]
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/VehicleController.java:581: warning: no description for @return
     * @return
       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/VehicleController.java:603: warning: no description for @return
     * @return
       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/VehicleController.java:624: warning: no @param for vid
    public VehicleShow setSecurityPassword(@PathVariable("vid") int vid,@RequestBody Vehicle vehicle,HttpServletRequest request) throws HttpException{
                       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/VehicleController.java:624: warning: no @param for vehicle
    public VehicleShow setSecurityPassword(@PathVariable("vid") int vid,@RequestBody Vehicle vehicle,HttpServletRequest request) throws HttpException{
                       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/VehicleController.java:624: warning: no @param for request
    public VehicleShow setSecurityPassword(@PathVariable("vid") int vid,@RequestBody Vehicle vehicle,HttpServletRequest request) throws HttpException{
                       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/VehicleController.java:624: warning: no @return
    public VehicleShow setSecurityPassword(@PathVariable("vid") int vid,@RequestBody Vehicle vehicle,HttpServletRequest request) throws HttpException{
                       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/controller/VehicleController.java:624: warning: no @throws for com.hp.briair.utils.HttpException
    public VehicleShow setSecurityPassword(@PathVariable("vid") int vid,@RequestBody Vehicle vehicle,HttpServletRequest request) throws HttpException{

**Comment by AceBear** [comment]
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/utils/SFTPUtil.java:25: warning: no @throws for com.jcraft.jsch.JSchException
    public ChannelSftp connect(String host, int port, String username,String password) throws JSchException {
                       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/utils/SFTPUtil.java:80: warning: no @return
    public boolean download(String directory, String downloadFile,OutputStream os, ChannelSftp sftp) {

**Comment by AceBear** [comment]
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/utils/ValidateCode.java:115: warning: no description for @param
     * @param path
       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/utils/ValidateCode.java:116: warning: no description for @throws
     * @throws IOException
       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/utils/ValidateCode.java:125: warning: no description for @param
     * @param sos
       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/utils/ValidateCode.java:126: warning: no description for @throws
     * @throws IOException
       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/utils/ValidateCode.java:135: warning: no description for @return
     * @return
       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/utils/ValidateCode.java:136: warning: no description for @throws
     * @throws Exception
       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/utils/ValidateCode.java:144: warning: no description for @return
     * @return
       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/utils/ValidateCode.java:145: warning: no description for @throws
     * @throws Exception
       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/utils/ValidateCode.java:153: warning: no description for @param
     * @param path
       ^
/home/travis/build/HP-Enterprise/BriAir/src/main/java/com/hp/briair/utils/ValidateCode.java:154: warning: no description for @throws
     * @throws IOException
       ^

**Comment by liuyakun** [comment]
消除部分警告  6fa3911682daaf6efa30ca90705c3676081b889c

**Comment by TeemolSparrow** [comment]
已消除相关警告
