### ISSUE TITLE
图形验证码：验证码生成以及验证码判断API

### ISSUE THREAD

**Issue by jiangli0509** [HP-Enterprise/BriAir#714]
* 生成验证码API：
 * 生成图片验证码
 * 保存图片
 * 生成一个唯一值作为验证码的key，存入redis，30's过期
 * 返回key和图片路径

* 验证码判断API：
 * 根据传入了key和验证码在redis里判断是否正确
 * 返回验证成功/失败

**Comment by Liujingguo91year** [comment]
已完成    e1e9c8c1

**Comment by AceBear** [comment]
@jiangli0509 这个任务比较复杂,以后可以考虑拆得更细一些

**Comment by Liujingguo91year** [comment]
已添加删除图片功能   d821311f29d566cd63ba474ff42c76f1e1482286

**Comment by tiandashen** [comment]
![ee](https://cloud.githubusercontent.com/assets/13448617/10724161/2544845c-7bfd-11e5-89d0-6dee3f3338ec.jpg)
这个path的值是不会改变的，他是在赏一个方法里被赋值了，而这个方法里并没有赋值，报空指针
![eee](https://cloud.githubusercontent.com/assets/13448617/10724206/8390b79c-7bfd-11e5-9f17-839439751bd2.jpg)
而且这样测试是一定能通过的。。。

**Comment by Liujingguo91year** [comment]
对图片保存路径做了修改，解决空指针问题。。。  88f29cf8
