### ISSUE TITLE
JavaDoc 升级

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#730]
参考 #729 进行JAVADOC的调整

+ 所有Controller( PageController除外 ),如果返回集合类,需要返回带泛型参数的,这样javadoc生成时,会有一个链接,方便其它人员查看返回内容
+ Controller类返回值涉及的内容,增加一个头部的说明

@jiangli0509 @TeemolSparrow  @Septemberwh ~~每人挑3个~~每人挑4个, 余下的一个给 @flowweerr

**Comment by jiangli0509** [comment]
UserController、VehicleController、OrganizationController

**Comment by Septemberwh** [comment]
LoginController,TerminalController,UploadController

**Comment by TeemolSparrow** [comment]
AuthorityController、MessageController、MQController

**Comment by jiangli0509** [comment]
已完成 91d0a61e

**Comment by flowweerr** [comment]
AuthorityController

**Comment by flowweerr** [comment]
已完成
