### ISSUE TITLE
FrontPage BUG：Load timeout for modules

### ISSUE THREAD

**Issue by jiangli0509** [HP-Enterprise/BriAir#737]
![image](https://cloud.githubusercontent.com/assets/5874912/10686268/eff04896-7994-11e5-905f-ba38483172dc.png)
打开登录页面N次出现这个bug,然后页面一片空白。

**Comment by AceBear** [comment]
网络问题,找网管,或中国电信解决

**Comment by jiangli0509** [comment]
这不是网络问题 在同样的网络条件下我可以良好的打开github

**Comment by AceBear** [comment]
+ 我们现在办公室的网络的确就有些断断续续
+ 同样去吃一样的东西,有人没拉肚子,不能代表食物就是卫生达标的
