### ISSUE TITLE
测试用例:补全TBoxTest的测试用例

### ISSUE THREAD

**Issue by jiangli0509** [HP-Enterprise/BriAir#738]
* 补全修改、删除、查找测试用例(调用TBoxMgr)。
* 测试发现bug修复。
参考 #702 
分支- dev-TboxCRUD#702

**Comment by wangh2015** [comment]
ec307c094dfb676e85d075fc34fe76cebac38161 findTBox()方法报错，其他方法已经测试

EntityManager is closed
java.lang.IllegalStateException: EntityManager is closed
