### ISSUE TITLE
V0.9 组织管理 新增组织成功后，新增组织窗口未自动关闭

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#744]
路径：组织管理
操作：新增一个组织（名称和编码不重复）并点击保存按钮
结果：新增组织窗口未自动关闭
期望：新增组织成功后，窗口应该自动关闭。并且新增的组织数据显示在列表中

**Comment by TeemolSparrow** [comment]
此问题未复现，请在下个版本复测

**Comment by wjgao** [comment]
在V0.10版本中此问题已处理，复测通过，关闭
