### ISSUE TITLE
V0.9 注销功能现实不正常，见描述

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#745]
路径：车联网平台首页
前提：某个用户已成功登陆进车联网平台
操作：点击平台右上角的“注销”按钮
结果：该用户名字依然显示出来，而且页面未跳转到用户注册页面。此时再任意点击平台首页按钮，页面跳转到用户注册页面，但是该用户的用户名和密码显示在用户名和密码输入框中
期望：点击“注销”按钮后，当前用户应该退出平台，且页面跳转回用户注册首页

**Comment by wjgao** [comment]
在V0.9版本中，点击注销按钮后要刷新页面才能退出系统

**Comment by Septemberwh** [comment]
3cd6b944已完成

**Comment by wjgao** [comment]
在V0.10版本中此问题已处理，复测通过，关闭
