### ISSUE TITLE
V0.9 组织管理 所有的弹出对话框和窗口保存后均未自动关闭

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#746]
现象：组织管理 所有的弹出对话框和窗口保存后均未自动关闭
期望：点击保存按钮后，对话框和 窗口均要自动关闭，并且在列表中的数据及时更新显示出来

**Comment by Septemberwh** [comment]
在最新版以实现

**Comment by wjgao** [comment]
在V0.10版本中此问题已处理，复测通过，关闭
