### ISSUE TITLE
V0.9 组织管理-权限组维护 无法添加用户

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#747]
路径：组织管理-权限组维护列表页面
操作：点击添加按钮，再在弹出的窗口中点击添加按钮，再关闭窗口
结果：权限组成员列表中无任何数据
期望：添加人员成功后，权限组成员列表中应该显示出添加成功的人员数据

**Comment by wangh2015** [comment]
已测试，可以增加用户到权限组，只是查询用户 AuthorityGroupRepository 中findUser(int oid, int agid)参数和@Query 对应错误，导致查询权限组用户列表页面始终无数据

**Comment by TeemolSparrow** [comment]
由于权限组成员查询方法bug造成，实际已添加进去，现已修复

**Comment by wjgao** [comment]
在V0.10版本中此问题已处理，复测通过，关闭
