### ISSUE TITLE
V0.9 用户管理 修改窗口修改用户属性后点击保存按钮，数据未修改成功

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#748]
路径：用户管理-修改窗口
操作：任意修改用户属性，比如昵称，然后点击保存按钮
结果：修改窗口自动关闭，但是在列表中该用户的昵称还是修改前的数据
期望：修改功能正常实现

**Comment by Septemberwh** [comment]
最新版本已实现

**Comment by wjgao** [comment]
在V0.10版本中此问题已处理，复测通过，关闭
