### ISSUE TITLE
V0.9 组织管理-详情页面 移除用户和车辆时应该有提示对话框出现

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#750]
路径：组织管理-详情页面
操作：在“用户信息”和“车辆信息”区域点击移除按钮
结果：用户和车辆被成功删除
期望：在点击移除按钮后，在当前页面上方应该弹出是否确认删除的提示对话框，点击确认按钮后，才能删除用户和车辆数据

**Comment by Septemberwh** [comment]
facbfa7f 已完成

**Comment by wjgao** [comment]
在V0.10版本中此问题已处理，复测通过，关闭
