### ISSUE TITLE
V0.9 组织管理-添加权限组 未显示出权限数据

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#754]
路径：组织管理-组织详情页面的权限组列表区域
操作：添加权限组时输入正确的权限组名称后至少选中1个权限并保存成功，关闭添加权限组窗口
结果：权限组列表中的“权限”栏未显示出权限名称
期望：被选中的权限名称能正常显示出来

**Comment by AceBear** [comment]
#485 意外覆盖了 #511 的功能

**Comment by wjgao** [comment]
在V0.10版本中此问题已处理，复测通过，关闭
