### ISSUE TITLE
V0.9 系统更新 终端类型名称不能为空，现状是可以为空

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#756]
路径：系统更新-终端类型-修改页面
操作：清空终端类型名称再点击保存按钮
结果：保存成功，终端类型列表中无名称显示（见下图A1），再返回到系统更新模块页面，标签显示有问题（见下图A2）
![a1](https://cloud.githubusercontent.com/assets/13793913/10719551/e1acdfaa-7bc5-11e5-88ef-b301db12bc95.jpg)
![a2](https://cloud.githubusercontent.com/assets/13793913/10719554/eacf9064-7bc5-11e5-85b3-88f3666d9178.jpg)
期望：终端类型名称不能为空，为空时不能保存成功

**Comment by liuyakun** [comment]
已完成  39dd2bddf9e57252740a2709852d4a90e3ff70e8

**Comment by wjgao** [comment]
在V0.10版本中此问题已处理，复测通过，关闭
