### ISSUE TITLE
V0.9 系统更新 翻页号码未显示出来

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#757]
路径：系统更新模块主页面
前提：列表中的数据只有1条
现象：翻页号码未显示出来，如下图所示
![a](https://cloud.githubusercontent.com/assets/13793913/10719583/6e2a0034-7bc6-11e5-91e1-aca332627ad6.jpg)
期望：只有一页数据时，翻页号码也应该显示出来，如下图所示
![b](https://cloud.githubusercontent.com/assets/13793913/10719589/80343f24-7bc6-11e5-9345-b3aeadf73bd0.jpg)
注意：系统更新有四个子标签页面

**Comment by Septemberwh** [comment]
没有数据时，不会有页面显示

**Comment by wjgao** [comment]
OK
