### ISSUE TITLE
V0.9 系统更新 删除对话框无法自动关闭

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#758]
路径：系统更新-终端类型
操作：点击删除按钮，再在弹出的对话框中点击确认按钮
结果：提示对话框未自动关闭而且列表中依然显示出被删除的数据（此时刷新页面就不显示了）
期望：在提示对话框中点击任意按钮，对话框都应该自动关闭，如果点击的是删除和确认按钮，那么不仅对话框自动关闭，列表中的数据也要同时不显示出来

**Comment by wjgao** [comment]
在下一个版本中复测，V0.9版本的代码与开发环境不一致

**Comment by Septemberwh** [comment]
最新版中没有发现此现象

**Comment by wjgao** [comment]
在V0.10版本中对话框可以自动关闭，但在系统更新-权限组成员，在删除对话框中点击删除按钮后，列表中的数据未及时删除，只能点击刷新按钮，被删除的数据才不显示出来

**Comment by wjgao** [comment]
在V0.10版本中此问题已处理，复测通过，关闭
