### ISSUE TITLE
V0.9 建议 系统更新 终端类型名称不能重复

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#759]
路径：系统更新
现象：终端名称可以重复，如下图所示
![a](https://cloud.githubusercontent.com/assets/13793913/10719905/47bfbca8-7bcc-11e5-8d0c-bb9fe1d70c46.jpg)
建议：终端类型名称不能重复，避免上传文件出现不可预见的问题

**Comment by liuyakun** [comment]
已完成  39dd2bddf9e57252740a2709852d4a90e3ff70e8

**Comment by wjgao** [comment]
在V0.10版本中此问题已处理，复测通过，关闭
