### ISSUE TITLE
V0.9 建议 系统更新 终端类型名称长度不要超过10个字符

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#760]
路径：系统更新
现象：终端类型名称长度超过10个字符后，标签名称超出显示框了，如下图所示
![a](https://cloud.githubusercontent.com/assets/13793913/10719955/ca1162ba-7bcc-11e5-8d22-a8f65538b64d.jpg)
建议：终端类型名称长度不要超过10个字符，在添加和修改页面终端类型名称超过10个字符时应该在输入框下方出现提示内容为 终端类型名称长度不能超过10个字符，且添加或修改不成功

**Comment by liuyakun** [comment]
已完成  39dd2bddf9e57252740a2709852d4a90e3ff70e8

**Comment by wjgao** [comment]
在V0.10版本中此问题已处理，复测通过，关闭
