### ISSUE TITLE
V0.9 系统更新 列表中未显示出已上传的文件

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#762]
路径：系统更新
操作：以Android为例，点击上传按钮，选择终端类型为Android，适用版本任意输入，再选中一个app文件后点击确定按钮，如下图所示
![a1](https://cloud.githubusercontent.com/assets/13793913/10720092/4f051fec-7bce-11e5-9922-1a5e7ce29d1f.jpg)
结果：上传窗口自动关闭，系统更新的Android标签页列表中无数据显示出来
期望：点击确定按钮并且窗口自动关闭后，上传的文件显示在列表中

**Comment by Septemberwh** [comment]
在最新版已修复

**Comment by wjgao** [comment]
在V0.10版本中此问题依然存在，上传后列表中无显示

**Comment by Septemberwh** [comment]
因为在你测试的linux服务器中没有配置**SFTP**，所以上传文件时没有效果的。现在添加了对**SFTP**没有配置的异常处理

**Comment by wjgao** [comment]
在V0.10版本中此问题已处理，复测通过，关闭
