### ISSUE TITLE
SMS验证码修订

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#769]
背景信息: 客户端需要支持使用手机号直接注册用户的方式,为此,需要在用户注册前验证手机号

方案: 修订2个API
```
/api/user/{uid}/phone/{sim}/verify
/api/user/{uid}/phone/{sim}/verify/{code}
```
使其支持uid=0的情况,当uid=0时,表示此用户并不是一个真正在系统中存在的用户,但仍然可以发送验证短消息,并随后进行验证功能

进行系统分析,确认哪些CLASS需要修订,哪些CLASS需要新增,哪些CLASS需要删除

**Comment by TeemolSparrow** [comment]
已完成此功能修订
