### ISSUE TITLE
注册第二步需要改进

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#77]
![image](https://cloud.githubusercontent.com/assets/5030312/9538912/832f6ed8-4d7c-11e5-971b-a34e1d438e90.png)

+ 昵称栏 意图不明确,需要加一个LABEL明确指出昵称栏
+ 昵称默认不要使用全数字,直接使用"用户名"或后缀增加一个数字,比如用注册了 mike,那么昵称可以是mike2015, mike112这样的
+ *服务和隐私政策*在哪儿可以看到?

参见 #13

**Comment by bingshe** [comment]
昵称可加粗或者修改颜色。
