### ISSUE TITLE
V0.9 组织管理-修改组织信息 点击取消按钮，窗口出现XX不能为空的提示信息

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#778]
路径：组织管理-修改组织信息
操作：只点击取消按钮
结果：在修改组织信息窗口中的“组织名称”和“组织简码”输入框中的值被清空，而且下方出现XX不能为空的提示信息，如下图所示
![a](https://cloud.githubusercontent.com/assets/13793913/10724769/edc85a26-7c01-11e5-8d87-d0e92be991b2.jpg)
期望：点击取消按钮，输入框中的数据不会被清空

**Comment by AceBear** [comment]
和 @wjgao 沟通一下,确认一下问题

**Comment by wjgao** [comment]
在V0.10版本中此问题已处理，复测通过，关闭
