### ISSUE TITLE
审计日志

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#804]
所有的API层操作,都需要进行记录,这通常叫"审计日志"

+ 无论成功或失败的调用,都需要记录
+ 记录中还需包括操作人,操作时间,操作的API
+ 记录中不应包含敏感的信息
+ 只允许特定权限的人员可以查看审计日志

先进行设计
1. 技术方案
2. 需要修改哪几个CLASS, 新增几个CLASS(包括JS端)
3. 写好CLASS及其中主要的方法定义包括说明
4. 必要的单元测试
5. 分解任务

**Comment by wangh2015** [comment]
日志查询已完成，已测试。  日志记录异常处理问题在解决中

**Comment by wangh2015** [comment]
增加异常写入，解决unchecked 警告

**Comment by wangh2015** [comment]
@Liujingguo91year  完善审计日志，新增返回值（若api抛出exception，则日志会有两条请求记录，将两条记录合并，做好异常标识）

**Comment by Liujingguo91year** [comment]
完成审计日志合并，以及异常标识
#e6a18d12

**Comment by AceBear** [comment]
@Septemberwh 实现一个前端界面,用于查询审计日志
