### ISSUE TITLE
BUG：用户注册过程报错

### ISSUE THREAD

**Issue by TeemolSparrow** [HP-Enterprise/BriAir#807]
用户注册过程中，界面显示用户注册成功，此用户信息也录入到了系统中，但后台会报一个空指针错误

![qq 20151028110140](https://cloud.githubusercontent.com/assets/13936823/10778707/76086e96-7d63-11e5-9b34-e38f29e81c70.png)

![qq 20151028110310](https://cloud.githubusercontent.com/assets/13936823/10778715/8496739a-7d63-11e5-9549-4e49a58df202.png)

**Comment by Septemberwh** [comment]
做在了‘dev-#705’分支上
