### ISSUE TITLE
BUG：修改密码显示未授权

### ISSUE THREAD

**Issue by TeemolSparrow** [HP-Enterprise/BriAir#808]
路径：登录-验证-修改密码
操作：输入错误的密码，进入短信验证页面，验证通过后修改密码，点击确认按钮界面无反应，后台显示无权限
![qq 20151028111039](https://cloud.githubusercontent.com/assets/13936823/10778892/4973147e-7d65-11e5-9e91-85e687b6d1b5.png)

**Comment by tiandashen** [comment]
9dfd3908bf2b755e121183045aa5560d0574aad4
完成

**Comment by TeemolSparrow** [comment]
复测通过
