### ISSUE TITLE
编写接口文档

### ISSUE THREAD

**Issue by flowweerr** [HP-Enterprise/BriAir#821]
### 编写接口文档
 - 根据现有的API编写接口文档-controller，包括
   - AuthorityController 
   - CareRecordController 
   - LoginController 
   - MessageController 
   - MQController 
   - OrganizationController 
   - SlotController 
   - TBoxController 
   - TerminalController 
   - UploadController 
   - UserController  
   - VehicleController 
   - VehicleDataController
- 汪灏和刘经国1人分一半，商量好谁写哪个

**Comment by flowweerr** [comment]
@Liujingguo91year

**Comment by wangh2015** [comment]
AuthorityController
CareRecordController
LoginController
MessageController 
MQController
OrganizationController
我负责编写

**Comment by Liujingguo91year** [comment]
SlotController
SysdictController
TBoxController
TerminalController
UploadController
UserController
VehicleController
VehicleDataController

已完成
