### ISSUE TITLE
短信验证提示信息不准确

### ISSUE THREAD

**Issue by TeemolSparrow** [HP-Enterprise/BriAir#831]
现象：短信验证过程中，后台报“发送间隔不得小于120秒”，前端显示的是“发送短信失败”
建议：提示用户发送间隔不得小于120秒

![qq 20151029092412](https://cloud.githubusercontent.com/assets/13936823/10807824/2dd1a810-7e1f-11e5-957c-2987e25d04e6.png)
![qq 20151029092634](https://cloud.githubusercontent.com/assets/13936823/10807825/2df98d6c-7e1f-11e5-88c3-62337271f4c0.png)

**Comment by tiandashen** [comment]
791c3333337df26478e5766aa46890af7d7541fa
已完成
