### ISSUE TITLE
V0.10 用户注册 不输入验证码点击注册按钮 TOMCAT报错

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#882]
路径：用户注册页面
操作：不输入验证码，再点击注册按钮
结果：页面无反应，TOMCAT报错
期望：不输入验证码点击注册按钮时，在验证码输入框下方出现 请输入验证码 的提示信息

**Comment by liuyakun** [comment]
7dd7f06606430987d0343dd64bbd6ddc86c8b0f3 页面中已完成验证码非空验证

**Comment by liuyakun** [comment]
61344b0d772d27124f732a01680099cffed42878 完成验证码非空验证

**Comment by hanqiuwan** [comment]
测试已验证
