### ISSUE TITLE
V0.10 用户注册 清空验证码再点击注册按钮 提示内容不准确

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#883]
路径：用户注册页面
操作：输入验证码后再清空验证码接着点击注册按钮
结果：当前页面提示 输入的验证码错误, 请重新输入 的提示信息
期望：清空验证码并点击注册按钮 提示内容应该为 请输入验证码

**Comment by liuyakun** [comment]
已在 #882 中解决这个问题

**Comment by hanqiuwan** [comment]
测试已验证
