### ISSUE TITLE
Apple APN

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#898]
#1165

**Comment by jack-luj** [comment]
## 参考资料 
##### *http://ask.dcloud.net.cn/article/152*
##### *https://github.com/notnoop/java-apns8*
##### *http://my.oschina.net/crazyiter/blog/172795*
##### *https://github.com/RamosLi/dbay-apns-for-java*

**Comment by jack-luj** [comment]
转给@ZaiHang

**Comment by ZaiHang** [comment]
已经完成
