### ISSUE TITLE
V0.10 修改TBOX窗口名称错误

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#901]
路径：车辆管理-TBOX管理-修改TBOX窗口
现象：窗口名称错误，如下图所示
![a2](https://cloud.githubusercontent.com/assets/13793913/10901882/08295160-8231-11e5-9d68-90c3a9456e70.jpg)
期望：将名称改为 修改TBOX 即可

**Comment by juckie** [comment]
5eda4d284eb04cf5d974e700911a484cec44118a

**Comment by hanqiuwan** [comment]
测试已验证
