### ISSUE TITLE
v0.10 车辆管理-TBOX管理 添加页面输入重复的TBOX保存后，窗口关闭了

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#906]
路径：车辆管理-TBOX管理
前提：已存在TBOX-001数据
操作：在添加TBOX页面输入重复的TBOX数据，比如输入TBOX-001，点击保存按钮，此时在当前窗口的TBOX输入框下方出现  该tbox号码已存在 的信息（如下图所示），接着再次点击保存按钮
![a1](https://cloud.githubusercontent.com/assets/13793913/10902449/09b2293c-8239-11e5-9a47-3b677f624a3a.jpg)
结果：添加TBOX窗口自动关闭，新添加的数据未保存
期望：当TBOX数据重复时点击保存按钮，添加TBOX窗口不会关闭，必须输入不重复的TBOX数据才能添加成功和窗口自动关闭

**Comment by liuyakun** [comment]
5374735 修改TBox手机验证、备注验证，修改添加页面输入重复的TBox保存后，窗口关闭，修改TBox添加、修改时唯一性问题。

**Comment by hanqiuwan** [comment]
测试已验证
