### ISSUE TITLE
HTTP Login时返回更详细的错误

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#910]
登录失败时,我们现在只返回登录失败

要求修改逻辑,在返回的错误中能指示出更详细的原因:
+ 密码错误
+ 用户不存在

方案:
+ 修订 LoginController.login 方法,区别对待不同原因的登录错误
+ Identify.VerifyPassword 方法,区别对待不同原因的校验失败

**Comment by wangh2015** [comment]
86b4187916042ee236940159d79eba2f8e0666aa 已测试完成
