### ISSUE TITLE
V0.10  组织管理-权限组-维护 删除用户需要刷新页面才不显示数据

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#916]
路径：组织管理-权限组-维护
操作：删除用户数据，点击移除按钮
结果：用户依然显示在列表中，只有手动刷新页面，被删除的用户数据才不会显示在列表中
期望：自动删除并不显示出已被删除的用户数据

**Comment by TeemolSparrow** [comment]
与 #939 号bug相同

**Comment by hanqiuwan** [comment]
与 #939 号bug内容相同 已验证
