### ISSUE TITLE
V0.10 组织管理-权限组成员 必须手动刷新页面，列表中才不显示出被删除的用户数据

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#939]
路径：组织管理-维护-权限组成员列表页面
前提：列表中至少有一个用户数据
操作：在权限组成员列表中点击某行用户数据后面的删除移除按钮，在弹出的对话框中点击确定按钮
结果：该用户数据依然显示在列表中，必须手动刷新页面才会不显示出来
期望：在对话框中点击确定按钮后，列表中不会显示已被移除的用户数据

**Comment by hanqiuwan** [comment]
测试已验证
