### ISSUE TITLE
V0.10 组织管理-权限组成员 移除用户后，当前登录用户昵称未显示出来

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#940]
路径：组织管理-维护-权限组成员
操作：在权限组成员列表中点击移除按钮在弹出的对话框中点击确定按钮后再刷新页面
结果：当前页面右上角之前显示出来的当前已登录的用户昵称未显示，如下图所示
![a2](https://cloud.githubusercontent.com/assets/13793913/10928486/b1f979e2-82e3-11e5-9358-513828ceef27.jpg)
期望：任何操作都不会影响当登录用户的昵称显示功能

**Comment by liuyakun** [comment]
8457125acee2b54310a221593d0bae1f2f88b215  已修改权限组成员列表中点击移除未显示昵称问题

**Comment by hanqiuwan** [comment]
测试已验证
