### ISSUE TITLE
V0.10 车辆管理-保养记录 只能显示出10条数据，无翻页功能

### ISSUE THREAD

**Issue by wjgao** [HP-Enterprise/BriAir#948]
路径：车辆管理-保养记录列表页面
前提：列表中已存在10条保养记录数据，如下图所示
操作：继续添加保养记录
结果：列表中还是只显示出前10条数据，无翻页功能
期望：保养记录页面增加翻页功能，每页显示10条数据

**Comment by hanqiuwan** [comment]
测试已验证
