### ISSUE TITLE
BUG：创建权限组API需要抛出权限组重名异常

### ISSUE THREAD

**Issue by TeemolSparrow** [HP-Enterprise/BriAir#969]
#933

创建权限组API:[AuthorityController.java](https://github.com/HP-Enterprise/BriAir/blob/a95f3b9ad635759c8d65f12977968e3707a9b888/src/main/java/com/hp/briair/controller/AuthorityController.java#L148-L184)未进行权限组重名检查

**Comment by wangh2015** [comment]
已完成，已测试
