### ISSUE TITLE
BUG：用户验证过程bug

### ISSUE THREAD

**Issue by TeemolSparrow** [HP-Enterprise/BriAir#975]
用户验证过程中一直提示“发送间隔不得小于120秒”

![qq 20151105141336](https://cloud.githubusercontent.com/assets/13936823/10961326/80b38e64-83c8-11e5-800f-17fcf913ba77.png)

**Comment by AceBear** [comment]
![Test](http://group.store.qq.com/qun/V12e0jRu2ayF1W/V3t8j22G7H1OlZYUQw7/800?w5=1280&h5=640&rf=viewer_421)

**Comment by wangh2015** [comment]
已测试解决
