### ISSUE TITLE
保养预约

### ISSUE THREAD

**Issue by AceBear** [HP-Enterprise/BriAir#981]
1. 用户可以向某个4S店发送保养预约请求
2. 4S店收到后,可以接受预约,也可以拒绝预约.
3. 用户会收到通知消息,他的预约请求被批准了,或被拒绝了,如果是拒绝了,还需要附有简短的拒绝原因
4. 4S店可以查看历史预约记录

-----
先进行设计:
1. 方案概述
2. 接口设计,需要新增哪些API接口
3. 实现设计,哪些CLASS需要修改,哪些CLASS需要新增(如果有的话,哪些CLASS需要被删除)
4. 按第3步的设计编写CLASS的主要方法,不需要实现
5. 分解任务到method,编写成issues,委派给组员完成
6. 设计必要的单元测试任务

第3步完成后,召集大家进行评审,通过后,继续4~6步

REF #16

**Comment by wangh2015** [comment]
@AceBear  设计已做好  分支#981
